## CLEAN SNAPSHOT DATA EUROGATE

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

df = pd.read_csv("data/eurogate_all_snapshots.csv")

In [37]:
# print number of unique customsRefId
print(f"Number unique customsRefId: {df["customsRefId"].nunique()}")
# print number of unique containerId
print(f"Number of unique containerId: {df["containerId"].nunique()}")
# print number of unique lineCode
print(f"Number of unique lineCode: {df["lineCode"].nunique()}")
print(f"Unique lineCode: {df["lineCode"].unique()}")
# print number of unique iedCode and unique iedCode
print(f"Number of unique iedCode: {df["iedCode"].nunique()}")
print(f"Unique iedCode: {df["iedCode"].unique()}")
# print number of unique sizetypeIsoCode and unique sizetypeIsoCode
print(f"Number of unique sizetypeIsoCode:{df["sizetypeIsoCode"].nunique()}")
print(f"Unique sizetypeIsoCode:\n{df["sizetypeIsoCode"].unique()}")
# print number of unique typeCode and unique typeCode
print(f"Number of unique typeCode: {df["typeCode"].nunique()}")
print(f"Unique typeCode: {df["typeCode"].unique()}")
# print unique/number of unique TEU values and MGW values
print(f"Unique TEU values: {df["teu"].unique()}")
print(f"Number of unique TEU values: {df["teu"].nunique()}")
print(f"Unique MGW values: {df["mgw"].unique()}")
print(f"Number of unique MGW values: {df["mgw"].nunique()}")
print(f"Unique gross values: {df["gross"].unique()}")

Number unique customsRefId: 144942
Number of unique containerId: 146674
Number of unique lineCode: 19
Unique lineCode: [160   8  77  68  28  32  91  70  27  67 167 163   1  42 322  33 196  64
 161]
Number of unique iedCode: 2
Unique iedCode: ['IMPORT' 'EXPORT']
Number of unique sizetypeIsoCode:105
Unique sizetypeIsoCode:
['22K2' '22T0' '22T1' '22T3' '22R1' '45G1' '22U1' '22P3' '42U1' '42P3'
 'LEG1' '45R1' '45R4' '22G1' '22K7' 'L5G1' '42G1' '46U1' '22T6' '22GB'
 '45G0' '22KA' '22G0' '45R5' '4EG1' '45P9' '22GP' '45GP' '45R7' '45P3'
 '45P4' '49P0' '45R0' '25G1' '25A0' '25S5' '22G2' '46G1' '45G4' 'LEGB'
 '45G9' '26T6' '45U1' '22T2' '42GP' '46PM' '22G9' '22K5' '22T7' '22KX'
 '22TN' '22P4' '22P0' '22U0' '42UT' '42U0' '45U0' '45UT' '44U1' '45G2'
 '22A0' '45S3' '42GB' '45U6' '22UT' '45P0' '44P3' '45P1' '45RE' '22P8'
 '45P8' '22T5' '25G3' '25U1' '25G0' '25R1' '25K1' '25T1' '22SG' '42U6'
 '55G1' '25P7' '45R8' '25P3' '42P1' '42G0' '22K1' '45G3' '42R0' '22RE'
 '25G2' 'LEG8' '5EGB' 'LEG9' '45RB' '20T1' '42P2' '42P4' 'LNRB' '5NRB'
 '42P0' '25GB' '22UV' '22GD' '25GD']
Number of unique typeCode: 11
Unique typeCode: ['TK' 'RF' 'DC' 'OT' 'FC' 'DO' 'SR' 'PL' 'AC' 'OH' 'FR']
Unique TEU values: [1 2]
Number of unique TEU values: 2
Unique MGW values: [   nan 36000. 30480. 34000. 50000. 52500. 32500. 30482. 35000. 39000.
 45000.  3048. 24000.  3250. 21330.  3080.  3480. 22180. 32250. 32000.
 30470. 55000. 33020. 21480. 28260. 34500.  3045. 30448. 30880. 32400.
 32900. 60000. 31400. 30150. 30048. 40000. 31420.  5200. 52000. 32550.
 34800.  3040. 30488. 41210. 30490. 30580. 34888. 33250. 39489. 47370.
 30250. 28250.  2120. 30000. 56000.  3900.]
Number of unique MGW values: 55
Unique gross values: [27610. 21850. 21690. ...  9557. 22939. 19479.]

In [ ]:
# print number of nan values for mgw
print(f"Number of nan values for mgw: {df["mgw"].isna().sum()}")
# print number of non-nan values for mgw
print(f"Number of non-nan values for mgw: {df["mgw"].notna().sum()}")

#print number of nan values for gross
print(f"Number of nan values for gross: {df["gross"].isna().sum()}")
# print number of non-nan values for gross
print(f"Number of non-nan values for gross: {df["gross"].notna().sum()}")

Number of nan values for mgw: 760464
Number of non-nan values for mgw: 378375
Number of nan values for gross: 90
Number of non-nan values for gross: 1138749

In [46]:
# print csc unique values and count of each unique value
print(f"Unique csc values: {df["csc"].unique()}")
print(f"Count of each unique csc value: {df["csc"].value_counts()}")
# print originOfTransportCode unique values and count of each unique value
print(f"Unique originOfTransportCode values: {len(df["originOfTransportCode"].unique())}")
print(f"Count of each unique originOfTransportCode value: {df["originOfTransportCode"].value_counts()}")
# print the number of columns where arrivalPolCode is not the same as originOfTransportCode
print(f"Number of columns where arrivalPolCode is not the same as originOfTransportCode: {len(df[df["arrivalPolCode"] != df["originOfTransportCode"]])}")

# print unique values in arrivalType
print(f"Unique arrivalType values: {df["arrivalType"].unique()}")

# print unique values in arrivalVesselName and unique counts
print(f"Unique arrivalVesselName values: {len(df["arrivalVesselName"].unique())}")
print(f"Count of each unique arrivalVesselName value: {df["arrivalVesselName"].value_counts()}")

Unique csc values: [False]
Count of each unique csc value: csc
False    1138839
Name: count, dtype: int64
Unique originOfTransportCode values: 269
Count of each unique originOfTransportCode value: originOfTransportCode
CNSHA    157680
MYTPP    123594
CNYTN     93825
CNNGB     67717
SGSIN     61024
          ...
ESCAR         4
JPNGO         4
GHTKD         4
JPTYO         4
MVMLE         1
Name: count, Length: 268, dtype: int64
Number of columns where arrivalPolCode is not the same as originOfTransportCode: 66
Unique arrivalType values: ['OCEAN_CARRIER' 'FEEDER' 'SCHUTE' 'BINNEN']
Unique arrivalVesselName values: 244
Count of each unique arrivalVesselName value: arrivalVesselName
MILAN MAERSK          43429
MAJESTIC MAERSK       37256
AL ZUBARA             35930
CMA CGM CONCORDE      33283
EVELYN MAERSK         32900
                      ...
MSC BERANGERE             4
MSC BENEDETTA XIII        3
CSCL NEPTUNE              3
MSC ROMA                  2
MSC FATMA                 1
Name: count, Length: 244, dtype: int64

In [55]:
# print arrivalServiceName unique values and count of each unique value
print(f"Unique arrivalServiceName values: {len(df["arrivalServiceName"].unique())}")
print(f"Count of each unique arrivalServiceName value: {df["arrivalServiceName"].value_counts()}")
# print unique values in arrivalServiceCode and unique counts 
print(f"Unique arrivalServiceCode values: {len(df["arrivalServiceCode"].unique())}")
print(f"Count of each unique arrivalServiceCode value: {df["arrivalServiceCode"].value_counts()}")

# print number of non-NaN for departureTime and departureType
print(f"Number of non-NaN for departureTime: {df["departureTime"].notna().sum()}")
print(f"Number of non-NaN for departureType: {df["departureType"].notna().sum()}")
# print number of NaN for departureTime and departureType
print(f"Number of NaN for departureTime: {df["departureTime"].isna().sum()}")
print(f"Number of NaN for departureType: {df["departureType"].isna().sum()}")

Unique arrivalServiceName values: 41
Count of each unique arrivalServiceName value: arrivalServiceName
NE 2                                            134176
CMA CGM FAL3                                    118188
CMA CGM FAL 1                                   111826
2M AE7 / CONDOR                                 111261
Baltic Sea, etc (UNIFEEDER) FLZ                  76351
IOS - ME 1                                       70221
NE 4                                             58666
HSUD NEO SAMBA SAEC 1                            47877
MSC SWAN                                         39288
NEMO / AUSTRALIEN                                37820
SBX BALTIC UNIF/CMA/ OOCL                        34257
CMA CGM EPIC                                     32216
MAERSK Extra                                     29547
MSC IPAK                                         25842
SWX 2 SERVICE                                    24850
FLX FINLAND EXPRESS                              24787
LEVANTE                                          22518
CMA CGM FEMEX                                    20253
MAE EUROSAL/SAWC                                 14330
NE 2 / AE1                                       13849
NE 4 / AE 5                                      12822
WALTER LAUK                                      11415
MSC-EXTRA                                        11404
MAERSK E27                                        8291
MSC/ZIM ISRAEL                                    6222
NWL-Barge                                         5261
EUROMAR                                           5012
MSC GREECE TURKEY                                 4905
BOERDE                                            4885
Norwegen (NORTH SEA CONTAINER LINE)               3409
RFS FEEDER IE1                                    3010
X-PRESS FEEDER                                    2852
MSC SAF - SÜDAFRIKA                               2382
MSC NWC to IPAK                                   2160
Arctic Container Lines AS                         1839
PLX POLAND                                        1782
MSC EQUADOR/ BALTIC                               1598
MSC BRITANNIA                                      580
RFS FEEDER IE2                                     509
Norwegendienst Westküste                           283
Diverse (absolute Ausnahme NUR Hauptschiffe)        95
Name: count, dtype: int64
Unique arrivalServiceCode values: 38
Count of each unique arrivalServiceCode value: arrivalServiceCode
219    148025
152    118188
197    111826
182    111261
32      76351
220     71488
221     70221
186     47877
176     39288
195     37820
170     34257
218     32216
224     29547
156     28002
214     24850
211     24787
189     22518
202     20253
192     14330
146     11415
184     11404
223      8291
172      6222
78       5261
196      5012
154      4905
120      4885
83       3409
173      3010
105      2852
113      2382
37       1839
208      1782
215      1598
217       580
174       509
59        283
209        95
Name: count, dtype: int64
Number of non-NaN for departureTime: 716759
Number of non-NaN for departureType: 855835
Number of NaN for departureTime: 422080
Number of NaN for departureType: 283004

In [79]:
# print(f"First 5 unique non-NaN departureTime: {df["departureTime"].dropna().head()}")
print(f"Number of unique departureType values: {(df["departureType"].unique())}")
print(f"Unique destinationCode values: {len(df["destinationCode"].unique())}")
# print number of NaN for destinationCode
print(f"Number of NaN for destinationCode: {df["destinationCode"].isna().sum()}")
print(f"Number of non-NaN for destinationCode: {df["destinationCode"].notna().sum()}")

# print unique released values, count, number of NaN
print(f"Unique released values: {len(df["released"].unique())}")
print(f"Count of each unique released value: {df["released"].value_counts()}")
print(f"Number of NaN for released: {df["released"].isna().sum()}")
print(f"Number of non-NaN for released: {df["released"].notna().sum()}")

# print forwarderName unique values and count of each unique value
print(f"Unique forwarderName values: {(df["forwarderName"].unique())}")
print(f"Count of each unique forwarderName value: {df["forwarderName"].value_counts()}")
print(f"number of nan forwarderName values: {df["forwarderName"].isna().sum()}")
print(f"number of non-nan forwarderName values: {df["forwarderName"].notna().sum()}")

# print number of numberOfArrivalContainersOnVessel
print(f"Number of numberOfArrivalContainersOnVessel: {(df["numberOfArrivalContainersOnVessel"].unique())}")

# print number of unique numberOfRemainOnBoardContainersOnVessel and values
print(f"Number of unique numberOfRemainOnBoardContainersOnVessel: {(df["numberOfRemainOnBoardContainersOnVessel"].unique())}")

Number of unique departureType values: [nan 'TRUCK' 'RAIL' 'OCEAN_CARRIER' 'INTER_TERMINAL' 'FEEDER' 'SCHUTE'
 'BINNEN']
Unique destinationCode values: 14
Number of NaN for destinationCode: 1091720
Number of non-NaN for destinationCode: 47119
Unique released values: 2
Count of each unique released value: released
Y    747141
N    391698
Name: count, dtype: int64
Number of NaN for released: 0
Number of non-NaN for released: 1138839
Unique forwarderName values: [nan]
Count of each unique forwarderName value: Series([], Name: count, dtype: int64)
number of nan forwarderName values: 1138839
number of non-nan forwarderName values: 0
Number of numberOfArrivalContainersOnVessel: [3398  724  721 1629 1214  634  632  326  344 1331 1329  211 1892 3304
 3376 3080  374  665  112   47  100 3913 3914 3275 3278  698  463   52
  273  329  328  305  561  524  346 2692 1139 1138 1350  355  140   57
  474  623  619 1332 2997 3064  292  653   38   35   10  209 2426  871
   64   71  303  348   53 2485  699 2618  758  757  134  351  714  817
  408   62   37  179  121   87  626 3480 1596  842 1134  324  155 4035
 3771 4132 2515 2513  485  482   70 1304  961  120  820  591  221  492
 1087  470 1700 1831  982 1369  248 2697   56  838 3090  192  193 1600
 1598  258  146   45  310   91   75  802  456  157  814  361   69  307
  979  334  275  274  870  882  386  599  206  224  195 1191 1190   13
  427   63  404  216  254   41   96   59  690  262   43   34 1010   25
  920  153   68   49  287   76  436  440  869  159  176  302  491 1709
   40   26   20  270   81   80  101 2747  403  222   95  163  243   39
   22  308  647   48    2  879   55   46   27   77  183  123  213   74
    1  139  161 2814 3512 3392 1347 1187  154 3686 1957 2999 2010 1807
  521   66 1687 1686 2482 1203  271  125   16  333   73 1720 1813  683
  150 1247 1248   29  199  160  223  105  233  627  428  609   11 1445
  162 3030 2265 2546 1135  612   82  416  191   30  147   18  141  152
  108  203  256   67  198 3133  434  102  255  138    8   44 3335   92
  110   79  278   85   99  116 3058  173  227   31   19  398   32  241
  196  103  297  202   21 1281  197  811   97    3    5  137  707  429
  129  715   86  169    7    4  242  122  124   72   78   93   23  148
    9  133  158   54    6 3694  144 2907  109  259   12 2885  638  151
   89   83   88   90   65  910   28  117  965  669  260   17   14   50
  878   51 2586  238   24  285 3153  337  104   60  294  783 1380 1168
  414 1162 1874 2927 3446  716 3386  957 1577 1015  419  363  214  232
  184  156  728  145 2518 3089  115 3416  960  676 1763 1539  397 1884
  843  393  657  350  454  418 3112 1511  320  376 2143  662 3523 3195
 2439 1622 1045  799 3306  252]
Number of unique numberOfRemainOnBoardContainersOnVessel: [ 899  578 1638 1304 2230  289   45 3665  280 3114 4576 5386 4896  209
 1120  438    0  228 1465 1467 1466 3332 2127 1604  271 1018  323 1372
  860  404 3040 2781 2151 1026  142  302  227 1130 1479 5071 1972 1356
 2334  348    6 1264 1405 2735  258   11 1521  172 2135 2622  341 2228
  372  250  911 1557 2472  436   93  180  377 2806 1057 3030 4607 1909
  396  470 1238 5001 1101 2051  125 1354 2207  467 2371 3705  191 2883
 2474  339 1157 3789 5782 3359 1538 1033    2 2889  794 1103 1102 2342
  204  553  141  230 3076 1100  195  279 2977  158   98  346 1087 1689
 1069  292 2286  898  344 1854  128  137 1051  151 2579  968  171  168
 1362 1286  163  310  174 3560 1299  143  237 3017  218  101 2446  117
  253  189  241   86  383  251  318  223   94  157   47   21  216  457
  421 3968 1240  202  369  382  254  426  186  284   74   65 1919 1782
  217 2591  311   54  175  187  335  185  159  256  160   52 5946 2818
  198  208 1231 5588  130 2071 1388 1230  320 3262 3614 2441 2372  129
 1592 1098 2991  443 1440  454  211 1358 1129  306 1593  213  368  312
  381  364   62 2674  940 3343 1518  266  245 2169  153 1497 1580 3312
 3878 2409  328  112 1748   97   24  102  220  242  504   68   88 1083
  233  240  303  698 1024  161  867  259 1275  100  557  232 1337  293
  297   85   51  196  255   80  295  178  106 2390 1146 1246  393  683
  273  317  135  108  307   60  308 2264 2009  244  304 2714 1482 1484
  272  197   10  466  305  176  331  207  319  688  429  423 2123 3997
   44 1830 3039 2776 1044  476 2402  361  264   92 1042  491  203  193
 2784  315  148  451  691  118 2465  131  357  120 3225 1168  399  416
    1  463 2541  132  386 1309  627  121  299  336 1256 4798  257  236
  415  164   33  122  514  278  309 1207 2237 4594 1837  501  385  408
 1888 5325 4159 1432  684 5022  575  608 4310 1884 1404 3376  487  912
 1215  975 2467  376  595  781 1144  110 3409 5009 3068 5256 3480 2002
 2351 1210 1320 4398 1226  878  107  275  542   72 1526 1958  893 4848
  422 1784 1155  126  252 1191 2791 3502 3438 3389 1077 1003]

In [85]:
# print(f"Number of unique numberOfRemainOnBoardContainersOnVessel: {(df["numberOfRemainOnBoardContainersOnVessel"].unique())}")
# print numberOfDepartureContainersOnVessel unique values and count of each unique value
print(f"Number of unique numberOfDepartureContainersOnVessel: {(df["numberOfDepartureContainersOnVessel"].unique())}")
print(f"Count of each unique numberOfDepartureContainersOnVessel value: {df["numberOfDepartureContainersOnVessel"].value_counts()}")
# print number of unique numberOfDepartureContainersOnVessel and values
print(f"Number of unique numberOfDepartureContainersOnVessel: {(df["numberOfDepartureContainersOnVessel"].unique())}")

print(f"Number of snapshot_date: {len(df["snapshot_date"].unique())}")

Number of unique numberOfDepartureContainersOnVessel: [2120 2121  574 1525 1439 1216 1215 1208  489  502   91  176 1624 1617
 1458 1679 1678 1818 1817 1814    7  907   34    6   96 1472 1759 1758
 1756 2264 2263  746  915  882 1825    0  532  527  560  384 1317  895
  362 2218  951 1186 1151 1150  724  208  200   55  112 1074  389 1638
 1987  344  849  809  807   53   45   23  836  870  868 1124  266   67
  547  405 2967  679   81 1380  700  655  146  934  465 1304  927  925
  110   79   32   28   39   48  311  232   19  945 1536 1306 1296 1295
  633  597  285  169  118  998  866 1484    1  617   29 2479 2478 2475
  797   21 1223 1189  313   50  978  829  824  414  392 1467 1468  582
  391 1324  268  267  766  533  521 2063  447  427 2375 2370  543   59
  129  279  493  124  905  684  683  352  293  354  340  706  466    4
    2  563 1349 1348  577  433  431  669  444  620  117  292  339  322
  542   10  654  262  168  167  265  264  403   66   14  559  363  154
   35   11   22 1103  514  116 1528    3   26   25  114  207  241  106
  102  723  707  395  316  212   58  282  223  422 1373   84   80   27
   60   57   68  544 1968  506   89  226   97   90  103   13  917   69
  178  166   87  482  415  306  305   15  694  175  128   72   41   18
 1437 1629  238 1770 1769 1877   33  145  122  734 1924 1922  839 2084
 1565 1562 1485 1401 1402 1398 1632  485  216  193 1724 1723 1657 2010
 1271 1266  115   82  705   12 1314 1294 1676  847 1870 1867 1828 1800
  135   70  143  138  214   56   38  239  194  215  464  350   30  394
  471  177 2376 2421  372  371 1771  446 1092   77 1680  283   93  235
  100   61   52  209  201   54   49  249 1762  199  163   99 1046  148
  144 2125  196  656   47 2789  488   44    8  155   36 2100  458  406
  437  516    9  498  419   88   85  107   20   83  136  132   73  119
  530  108  101  161 1377    5   74  250  233  808  569  258   63   98
  139   51   64   42   71   24   37   65  333  319  636  661  121 2144
 1783 2176  123  518   17  539   40  864  946  375  137   31  149 1597
  133   78   95 1455  570  187  182  180  428 2620  141  192  134  162
  140  280  242  400 1110  343 1026   16  165  641 2090   75  600 1257
 1279 1211  937  854 1107 1240  157  638  409  999  281   76 1322 2506
 1874 1100  711  676  806  407  366 1079 1262  278  474 1803  504  318
  500  611  979  568  435 2035   62  594]
Count of each unique numberOfDepartureContainersOnVessel value: numberOfDepartureContainersOnVessel
0       41140
1536    37256
866     31485
1769    30528
1678    29372
        ...
165         1
979         1
568         1
62          1
343         1
Name: count, Length: 456, dtype: int64
Number of unique numberOfDepartureContainersOnVessel: [2120 2121  574 1525 1439 1216 1215 1208  489  502   91  176 1624 1617
 1458 1679 1678 1818 1817 1814    7  907   34    6   96 1472 1759 1758
 1756 2264 2263  746  915  882 1825    0  532  527  560  384 1317  895
  362 2218  951 1186 1151 1150  724  208  200   55  112 1074  389 1638
 1987  344  849  809  807   53   45   23  836  870  868 1124  266   67
  547  405 2967  679   81 1380  700  655  146  934  465 1304  927  925
  110   79   32   28   39   48  311  232   19  945 1536 1306 1296 1295
  633  597  285  169  118  998  866 1484    1  617   29 2479 2478 2475
  797   21 1223 1189  313   50  978  829  824  414  392 1467 1468  582
  391 1324  268  267  766  533  521 2063  447  427 2375 2370  543   59
  129  279  493  124  905  684  683  352  293  354  340  706  466    4
    2  563 1349 1348  577  433  431  669  444  620  117  292  339  322
  542   10  654  262  168  167  265  264  403   66   14  559  363  154
   35   11   22 1103  514  116 1528    3   26   25  114  207  241  106
  102  723  707  395  316  212   58  282  223  422 1373   84   80   27
   60   57   68  544 1968  506   89  226   97   90  103   13  917   69
  178  166   87  482  415  306  305   15  694  175  128   72   41   18
 1437 1629  238 1770 1769 1877   33  145  122  734 1924 1922  839 2084
 1565 1562 1485 1401 1402 1398 1632  485  216  193 1724 1723 1657 2010
 1271 1266  115   82  705   12 1314 1294 1676  847 1870 1867 1828 1800
  135   70  143  138  214   56   38  239  194  215  464  350   30  394
  471  177 2376 2421  372  371 1771  446 1092   77 1680  283   93  235
  100   61   52  209  201   54   49  249 1762  199  163   99 1046  148
  144 2125  196  656   47 2789  488   44    8  155   36 2100  458  406
  437  516    9  498  419   88   85  107   20   83  136  132   73  119
  530  108  101  161 1377    5   74  250  233  808  569  258   63   98
  139   51   64   42   71   24   37   65  333  319  636  661  121 2144
 1783 2176  123  518   17  539   40  864  946  375  137   31  149 1597
  133   78   95 1455  570  187  182  180  428 2620  141  192  134  162
  140  280  242  400 1110  343 1026   16  165  641 2090   75  600 1257
 1279 1211  937  854 1107 1240  157  638  409  999  281   76 1322 2506
 1874 1100  711  676  806  407  366 1079 1262  278  474 1803  504  318
  500  611  979  568  435 2035   62  594]
Number of snapshot_date: 54

In [86]:
# use python weather API to add columns for weather data to the eurogate_all_snapshots.csv file
import requests
import json
import pandas as pd
import numpy as np

INPUT_CSV = "data/eurogate_train.csv"
OUTPUT_CSV = "data/eurogate_train.csv"

# Eurogate Hamburg / Port of Hamburg approximate coordinates
LAT = 53.541
LON = 9.958
TIMEZONE = "Europe/Berlin"

HOURLY_VARS = [
    "temperature_2m",
    "relative_humidity_2m",
    "precipitation",
    "rain",
    "weather_code",
    "cloud_cover",
    "wind_speed_10m",
    "wind_gusts_10m"
]

df = pd.read_csv(INPUT_CSV)

df["weather_match_time"] = pd.to_datetime(df["arrivalTime"], errors="coerce", utc=True)

df["weather_hour"] = (
    df["weather_match_time"]
    .dt.tz_convert(TIMEZONE)
    .dt.tz_localize(None)
    .dt.round("h")
)

start_date = df["weather_hour"].min().date().isoformat()
end_date = df["weather_hour"].max().date().isoformat()

print(f"Fetching weather from {start_date} to {end_date}")

url = "https://archive-api.open-meteo.com/v1/archive"

params = {
    "latitude": LAT,
    "longitude": LON,
    "start_date": start_date,
    "end_date": end_date,
    "hourly": ",".join(HOURLY_VARS),
    "timezone": TIMEZONE,
    "temperature_unit": "celsius",
    "wind_speed_unit": "kmh",
    "precipitation_unit": "mm",
}

response = requests.get(url, params=params, timeout=60)
response.raise_for_status()

weather = pd.DataFrame(response.json()["hourly"])
weather["weather_time"] = pd.to_datetime(weather["time"])
weather = weather.drop(columns=["time"])

df_weather = df.merge(
    weather,
    left_on="weather_hour",
    right_on="weather_time",
    how="left"
)

df_weather["is_raining"] = (
    df_weather["precipitation"].fillna(0) > 0
).astype(int)

df_weather["bad_weather_score"] = (
    df_weather["is_raining"]
    + (df_weather["wind_gusts_10m"].fillna(0) > 30).astype(int)
    + (df_weather["cloud_cover"].fillna(0) > 80).astype(int)
)

df_weather.to_csv(OUTPUT_CSV, index=False)

print("Saved:", OUTPUT_CSV)

print("\nWeather missing fraction:")
weather_cols = HOURLY_VARS + ["is_raining", "bad_weather_score"]
print(df_weather[weather_cols].isna().mean().sort_values(ascending=False))

df_weather.head()

Fetching weather from 2024-06-23 to 2025-05-06
Saved: data/eurogate_train.csv

Weather missing fraction:
temperature_2m          0.0
relative_humidity_2m    0.0
precipitation           0.0
rain                    0.0
weather_code            0.0
cloud_cover             0.0
wind_speed_10m          0.0
wind_gusts_10m          0.0
is_raining              0.0
bad_weather_score       0.0
dtype: float64

,containerId,customsRefId,lineCode,iedCode,sizetypeIsoCode,typeCode,reefer,teu,mgw,gross,...,relative_humidity_2m,precipitation,rain,weather_code,cloud_cover,wind_speed_10m,wind_gusts_10m,weather_time,is_raining,bad_weather_score
0,AAMU2504013,ATB152104710320254851,160,IMPORT,22K2,TK,False,1,NaN,27610.0,...,36,0.0,0.0,0,0,2.6,16.9,2025-04-12 15:00:00,0,0
1,AAMU2504013,ATB152104710320254851,160,IMPORT,22K2,TK,False,1,NaN,27610.0,...,36,0.0,0.0,0,0,2.6,16.9,2025-04-12 15:00:00,0,0
2,AAMU2504013,ATB152104710320254851,160,IMPORT,22K2,TK,False,1,NaN,27610.0,...,36,0.0,0.0,0,0,2.6,16.9,2025-04-12 15:00:00,0,0
3,AAMU2504013,ATB152104710320254851,160,IMPORT,22K2,TK,False,1,NaN,27610.0,...,36,0.0,0.0,0,0,2.6,16.9,2025-04-12 15:00:00,0,0
4,AAMU2504013,ATB152104710320254851,160,IMPORT,22K2,TK,False,1,NaN,27610.0,...,36,0.0,0.0,0,0,2.6,16.9,2025-04-12 15:00:00,0,0

## START WORKING ON EUROGATE TRAIN

In [27]:
df = pd.read_csv("data/eurogate_train.csv")

In [28]:
# drop containerId, customsRefId from eurogate_train.csv
# df = df.drop(columns=["containerId", "customsRefId"])

# print unique values in iedCode
print(f"Unique iedCode values: {df["iedCode"].unique()}")
# # for iedCode, IMPORT->0, EXPORT->1
df["iedCode"] = df["iedCode"].map({"IMPORT": 0, "EXPORT": 1})
print(f"Unique iedCode values: {df["iedCode"].unique()}")

Unique iedCode values: ['IMPORT' 'EXPORT']
Unique iedCode values: [0 1]

In [29]:
# map typeCode ['TK', 'RF', 'DC', 'OT', 'FC', 'DO', 'SR', 'PL', 'AC', 'OH', 'FR'] to 0-9
df["typeCode"] = df["typeCode"].map({"TK": 0, "RF": 1, "DC": 2, "OT": 3, "FC": 4, "DO": 5, "SR": 6, "PL": 7, "AC": 8, "OH": 9, "FR": 10})
# print unique values in typeCode
print(f"Unique typeCode values: {df["typeCode"].unique()}")

Unique typeCode values: [ 0  1  2  3  4  5  6  7  8  9 10]

In [30]:
df = df.drop(columns=["containerId", "customsRefId"])

In [31]:
df["reefer"] = df["reefer"].map({False: 0, True: 1})
print(f"unique values in reefer column: {df["reefer"].unique()}")

unique values in reefer column: [0 1]

In [32]:
# df = pd.read_csv("data/eurogate_train.csv")
df = df.drop(columns=["mgw"])
df.to_csv("data/eurogate_train.csv")

In [33]:
from pandas.api.types import is_string_dtype
from pandas.api.types import is_numeric_dtype

In [ ]:
print(is_numeric_dtype(df['gross']))

True

In [35]:
df = df.drop(columns=["csc"])

In [36]:
df["arrivalType"] = df["arrivalType"].map({"OCEAN_CARRIER": 0, "FEEDER": 1, "SCHUTE": 2, "BINNEN": 3})

In [37]:
df.to_csv("data/eurogate_train.csv")

In [41]:
import numpy as np
print(f"unique values in departureType: {df["departureType"].unique()}")
df["departureType"] = df["departureType"].map({np.nan: np.nan, "TRUCK": 1, "RAIL": 2, "OCEAN_CARRIER": 3, "INTER_TERMINAL": 4, "FEEDER": 5, "SCHUTE": 6, "BINNEN": 7})

unique values in departureType: [nan 'TRUCK' 'RAIL' 'OCEAN_CARRIER' 'INTER_TERMINAL' 'FEEDER' 'SCHUTE'
 'BINNEN']

In [43]:
df.drop(columns=["destinationCode"])

,lineCode,iedCode,sizetypeIsoCode,typeCode,reefer,teu,gross,originOfTransportCode,arrivalTime,arrivalPolCode,...,departureTime,departureType,released,forwarderName,numberOfArrivalContainersOnVessel,numberOfRemainOnBoardContainersOnVessel,numberOfDepartureContainersOnVessel,snapshot_date,source_file,location_key
0,160,0,22K2,0,0,1,27610.0,CNSHA,2025-04-12 12:43:17+00:00,CNSHA,...,NaN,NaN,Y,NaN,3398,899,2120,2025-04-13,Containerdaten-2025-04-13_01.56.13.csv,23_15_8
1,160,0,22K2,0,0,1,27610.0,CNSHA,2025-04-12 12:43:17+00:00,CNSHA,...,NaN,NaN,Y,NaN,3398,899,2120,2025-04-14,Containerdaten-2025-04-14_01.56.13.csv,23_15_8
2,160,0,22K2,0,0,1,27610.0,CNSHA,2025-04-12 12:43:17+00:00,CNSHA,...,2025-04-14 15:40:06+00:00,1.0,Y,NaN,3398,899,2120,2025-04-15,Containerdaten-2025-04-15_01.55.44.csv,23_15_8
3,160,0,22K2,0,0,1,27610.0,CNSHA,2025-04-12 12:43:17+00:00,CNSHA,...,2025-04-14 15:40:06+00:00,1.0,Y,NaN,3398,899,2120,2025-04-16,Containerdaten-2025-04-16_01.55.44.csv,23_15_8
4,160,0,22K2,0,0,1,27610.0,CNSHA,2025-04-12 12:43:17+00:00,CNSHA,...,2025-04-14 15:40:06+00:00,1.0,Y,NaN,3398,899,2121,2025-04-17,Containerdaten-2025-04-17_01.55.30.csv,23_15_8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138834,67,0,45R1,1,1,2,20400.0,ILAST,2024-10-23 05:35:46+00:00,ILAST,...,2024-10-24 05:22:03+00:00,1.0,Y,NaN,262,2372,485,2024-10-27,Containerdaten-2024-10-27_01.55.36.csv,6_2_84
1138835,67,0,45R1,1,1,2,20400.0,ILAST,2024-10-23 05:35:46+00:00,ILAST,...,2024-10-24 05:22:03+00:00,1.0,Y,NaN,262,2372,485,2024-10-28,Containerdaten-2024-10-28_01.56.35.csv,6_2_84
1138836,67,0,45R1,1,1,2,20400.0,ILAST,2024-10-23 05:35:46+00:00,ILAST,...,2024-10-24 05:22:03+00:00,1.0,Y,NaN,262,2372,485,2024-10-29,Containerdaten-2024-10-29_01.55.43.csv,6_2_84
1138837,67,0,45R1,1,1,2,20400.0,ILAST,2024-10-23 05:35:46+00:00,ILAST,...,2024-10-24 05:22:03+00:00,1.0,Y,NaN,262,2372,485,2024-10-30,Containerdaten-2024-10-30_01.56.15.csv,6_2_84
1138838,67,0,45R1,1,1,2,20400.0,ILAST,2024-10-23 05:35:46+00:00,ILAST,...,2024-10-24 05:22:03+00:00,1.0,Y,NaN,262,2372,485,2024-10-31,Containerdaten-2024-10-31_01.55.54.csv,6_2_84

In [54]:
# use python weather API to add columns for weather data to the eurogate_all_snapshots.csv file
import requests
import json
import pandas as pd
import numpy as np

INPUT_CSV = "data/eurogate_train.csv"
OUTPUT_CSV = "data/eurogate_train.csv"

# Eurogate Hamburg / Port of Hamburg approximate coordinates
LAT = 53.541
LON = 9.958
TIMEZONE = "Europe/Berlin"

HOURLY_VARS = [
    "temperature_2m",
    "relative_humidity_2m",
    "precipitation",
    "rain",
    "weather_code",
    "cloud_cover",
    "wind_speed_10m",
    "wind_gusts_10m"
]

df = pd.read_csv(INPUT_CSV)

df["weather_match_time"] = pd.to_datetime(df["arrivalTime"], errors="coerce", utc=True)

df["weather_hour"] = (
    df["weather_match_time"]
    .dt.tz_convert(TIMEZONE)
    .dt.tz_localize(None)
    .dt.round("h")
)

start_date = df["weather_hour"].min().date().isoformat()
end_date = df["weather_hour"].max().date().isoformat()

print(f"Fetching weather from {start_date} to {end_date}")

url = "https://archive-api.open-meteo.com/v1/archive"

params = {
    "latitude": LAT,
    "longitude": LON,
    "start_date": start_date,
    "end_date": end_date,
    "hourly": ",".join(HOURLY_VARS),
    "timezone": TIMEZONE,
    "temperature_unit": "celsius",
    "wind_speed_unit": "kmh",
    "precipitation_unit": "mm",
}

response = requests.get(url, params=params, timeout=60)
response.raise_for_status()

weather = pd.DataFrame(response.json()["hourly"])
weather["weather_time"] = pd.to_datetime(weather["time"])
weather = weather.drop(columns=["time"])

df_weather = df.merge(
    weather,
    left_on="weather_hour",
    right_on="weather_time",
    how="left"
)

df_weather["is_raining"] = (
    df_weather["precipitation"].fillna(0) > 0
).astype(int)

df_weather["bad_weather_score"] = (
    df_weather["is_raining"]
    + (df_weather["wind_gusts_10m"].fillna(0) > 30).astype(int)
    + (df_weather["cloud_cover"].fillna(0) > 80).astype(int)
)

df_weather.to_csv(OUTPUT_CSV, index=False)

print("Saved:", OUTPUT_CSV)

print("\nWeather missing fraction:")
weather_cols = HOURLY_VARS + ["is_raining", "bad_weather_score"]
print(df_weather[weather_cols].isna().mean().sort_values(ascending=False))

df_weather.head()

Fetching weather from 2024-06-23 to 2025-05-06
Saved: data/eurogate_train.csv

Weather missing fraction:
temperature_2m          0.0
relative_humidity_2m    0.0
precipitation           0.0
rain                    0.0
weather_code            0.0
cloud_cover             0.0
wind_speed_10m          0.0
wind_gusts_10m          0.0
is_raining              0.0
bad_weather_score       0.0
dtype: float64

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,lineCode,iedCode,sizetypeIsoCode,typeCode,reefer,teu,gross,...,relative_humidity_2m,precipitation,rain,weather_code,cloud_cover,wind_speed_10m,wind_gusts_10m,weather_time,is_raining,bad_weather_score
0,0,0,0,160,0,22K2,0,0,1,27610.0,...,36,0.0,0.0,0,0,2.6,16.9,2025-04-12 15:00:00,0,0
1,1,1,1,160,0,22K2,0,0,1,27610.0,...,36,0.0,0.0,0,0,2.6,16.9,2025-04-12 15:00:00,0,0
2,2,2,2,160,0,22K2,0,0,1,27610.0,...,36,0.0,0.0,0,0,2.6,16.9,2025-04-12 15:00:00,0,0
3,3,3,3,160,0,22K2,0,0,1,27610.0,...,36,0.0,0.0,0,0,2.6,16.9,2025-04-12 15:00:00,0,0
4,4,4,4,160,0,22K2,0,0,1,27610.0,...,36,0.0,0.0,0,0,2.6,16.9,2025-04-12 15:00:00,0,0

In [48]:
df["released"] = df["released"].map({'Y': 1, 'N':0})
print(df["released"].unique())

[1 0]

In [51]:
# df.to_csv("data/eurogate_train.csv")
print(df["forwarderName"].unique())
df.drop(columns=["forwarderName"])
df.to_csv("data/eurogate_train.csv")

[nan]

In [52]:
print(df["snapshot_date"].unique())

['2025-04-13' '2025-04-14' '2025-04-15' '2025-04-16' '2025-04-17'
 '2025-04-18' '2025-04-19' '2025-04-20' '2025-04-21' '2025-04-22'
 '2025-04-23' '2025-04-24' '2025-04-01' '2025-04-02' '2025-04-03'
 '2025-04-04' '2025-05-06' '2025-04-05' '2025-04-06' '2025-04-07'
 '2025-04-08' '2025-04-09' '2025-04-10' '2025-04-11' '2025-04-12'
 '2024-10-31' '2024-11-01' '2024-11-02' '2024-11-03' '2024-11-04'
 '2024-11-05' '2024-11-06' '2024-11-07' '2024-11-08' '2024-11-09'
 '2025-05-03' '2025-05-04' '2025-05-05' '2025-04-26' '2025-04-27'
 '2025-04-28' '2025-04-29' '2025-04-30' '2025-05-01' '2025-04-25'
 '2024-11-10' '2024-11-11' '2024-11-12' '2024-11-13' '2024-11-14'
 '2024-10-27' '2024-10-28' '2024-10-29' '2024-10-30']

In [53]:
df.drop(columns=["source_file"])
df.drop(columns=["location_key"])
df.to_csv("data/eurogate_train.csv")

In [63]:
df = pd.read_csv("data/eurogate_train.csv")
df.drop(columns=["source_file"])
df.drop(columns=["location_key"])
df.to_csv("data/eurogate_train.csv")

In [56]:
df = pd.read_csv("data/eurogate_train.csv")
df.drop(columns=["Unnamed: 0.2", "Unnamed: 0.1", "Unnamed: 0"])
df.to_csv("data/eurogate_train.csv")

In [62]:
print(df["arrivalPolCode"].unique())
print(len(df["arrivalPolCode"].unique()))

['CNSHA' 'GBLGP' 'INMUN' 'NLRTM' 'FIKTK' 'LTKLJ' 'THLCH' 'SGSIN' 'CNTAO'
 'FIRAU' 'EGPSD' 'DEHAM' 'DKCPH' 'DKAAR' 'CNYTN' 'ARBUE' 'UYMVD' 'NOEGE'
 'DEBRV' 'TRGEB' 'PLGDN' 'EGALY' 'GBSOU' 'LKCMB' 'GRPIR' 'EETLL' 'INENR'
 'CNNGB' 'TRAVC' 'INNSA' 'BRSSZ' 'NOAES' 'MAPTM' 'MAAGA' 'CNXMN' 'DKFRC'
 'BRPNG' 'SEGOT' 'CIABJ' 'MYTPP' 'CISPY' 'PLGDY' 'INHZA' 'CATOR' 'AEJEA'
 'CNTXG' 'SENRK' 'CNSHN' 'TRALI' 'FIHEL' 'SETGC' 'SEGVX' 'MACAS' 'LVRUT'
 'GBFXT' 'USMSY' 'MAMED' 'TRMER' 'NOFRK' 'DEWVN' 'DEMID' 'DECTB' 'TRISK'
 'BEANR' 'DEBWE' 'SENCS' 'BRRIG' 'SESDL' 'SEAGH' 'MXVER' 'DEEGW' 'PLDCT'
 'ITSAL' 'SESTO' 'MTMLA' 'TRGEM' 'PKKHI' 'LBBEY' 'NOBVK' 'GBTIL' 'FRLEH'
 'DEFAB' 'SEHAD' 'NOBGO' 'NOKST' 'DEEGB' 'PLSZZ' 'DEMAG' 'DECTT' 'AUFRE'
 'NOSAU' 'USHOU' 'AUADL' 'EEMUG' 'MXATM' 'SEKTH' 'TRIST' 'KRPUS' 'SEAHU'
 'NZNPE' 'DENTB' 'PKBQM' 'PHGES' 'INNML' 'ESLPA' 'ILASH' 'TRIZM' 'DJJIB'
 'OMSLL' 'NOHAU' 'ILHBT' 'NLMV2' 'SEPCT' 'FIVCT' 'EGDAM' 'ZADUR' 'NLDDN'
 'ESVGO' 'INHAL' 'PEPAI' 'MGTMM' 'INCCU' 'MYPKG' 'USMIA' 'AEKHL' 'DEHLH'
 'MYPEN' 'EGEDK' 'ILHFA' 'BDCGP' 'CASJB' 'DECTA' 'USEWR' 'AUMEL' 'LVBCT'
 'ESMTV' 'CLVAP' 'CNNSH' 'ESALG' 'PAMIT' 'CNNSA' 'FIKM' 'MMRGN' 'VNDAD'
 'NOSCT' 'DEHAJ' 'PHDVO' 'USORF' 'INTUT' 'GEBUS' 'LVBCR' 'PABLB' 'PLBCT'
 'NOLAR' 'CMDLA' 'CNDLC' 'CNFOC' 'NOMSS' 'HKHKG' 'MTMAR' 'USBAL' 'NGTIN'
 'ZACPT' 'VNHPH' 'KHKOS' 'USLAX' 'GHTKD' 'QAHMD' 'IDBLW' 'TRTEK' 'VNVUT'
 'JPHKT' 'ESCAR' 'NODRM' 'DKCSC' 'COTRB' 'NOMAY' 'INCOK' 'DKACT' 'VNUIH'
 'NOFUS' 'NOIKR' 'SAJED' 'TRAYT' 'USBOS' 'REPDG' nan 'NOTAE' 'PAROD'
 'KEMBA' 'IDSUB' 'MZBEW' 'NZBLU' 'PTSIE' 'PECLL' 'IDPNJ' 'BHKBS' 'SAJUB'
 'GRSKG' 'ECGYE' 'CNSWA' 'INVTZ' 'NOSKU' 'CLCNL' 'INPRT' 'AUSYD' 'LRMLW'
 'PACTB' 'GHTEM' 'NOFRO' 'JPUKB' 'JPYOK' 'FRMTX' 'ESVLC' 'DKKAT' 'MVMLE'
 'DKAAL' 'AEAUH' 'TGLFW' 'COBUN' 'CAVAN' 'IDJKT' 'USSEA' 'GTPBR' 'ZAPLZ'
 'THSGZ' 'JPTYO' 'BRAES' 'TZDAR' 'ZAZBA' 'TWKHH' 'JOAQJ' 'ILAST' 'NLAP2'
 'NOGJM' 'SESOE' 'LVRIX' 'JPTKY' 'COSMR' 'ECPBO' 'SAKAC' 'MUPLU' 'SYLTK'
 'USSAV' 'NAWVB' 'ESSCT' 'NZNSN' 'PEPIO' 'NLVLI' 'CLARI' 'JPMYJ' 'CAMTR'
 'USOAK' 'IDMAK' 'JPOSA' 'USCHS' 'TRGIR' 'DZALG' 'TWTXG' 'BJCOO' 'JPKNZ'
 'JPNGO' 'TNTUN' 'GEPTI' 'SVAQJ' 'KWSAA' 'BRVLC' 'FIKTS' 'NOORK']
269

In [ ]:
df = df.drop(columns=["Unnamed: 0.3", "Unnamed: 0.2", "Unnamed: 0.1", "Unnamed: 0", "source_file", "location_key"])
print(df.head())
df.to_csv("data/eurogate_train.csv")

In [71]:
df = df.drop(columns=["forwarderName", "destinationCode"])
df.to_csv("data/eurogate_train.csv")

In [81]:
print(is_numeric_dtype(df['snapshot_date']))

False

In [103]:
current_row = "weather_time"

null_total = df[current_row].isna().sum()
not_null = df[current_row].notna().sum()
total_rows = null_total+not_null
null_percent = null_total / (total_rows)

print(f"percent null: {null_percent}")

count_1 = df[current_row].value_counts()[0]
print(f"percent first value: {count_1/total_rows}")

count_2 = df[current_row].value_counts()[1]
count_3 = df[current_row].value_counts()[2]
count_4 = df[current_row].value_counts()[3]
count_5 = df[current_row].value_counts()[4]
top_5_count = count_1 + count_2 + count_3 + count_4 + count_5
print(f"percent first five value: {top_5_count/total_rows}")

percent null: 0.0
percent first value: 0.0025701613660930123
percent first five value: 0.012041210390581987

/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_47195/359117045.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_1 = df[current_row].value_counts()[0]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_47195/359117045.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_2 = df[current_row].value_counts()[1]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_47195/359117045.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_3 = df[current_row].value_counts()[2]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_47195/359117045.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_4 = df[current_row].value_counts()[3]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_47195/359117045.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_5 = df[current_row].value_counts()[4]

In [108]:
print(df["weather_time"].unique()[0])

2025-04-12 15:00:00

In [109]:
df = df.drop(columns = ["weather_time"])
df.to_csv("data/eurogate_train.csv")

In [ ]:
df = pd.read_csv("data/eurogate_train.csv")
print(df.head(5))

   Unnamed: 0  lineCode  iedCode sizetypeIsoCode  typeCode  reefer  teu  \
0           0       160        0            22K2         0       0    1
1           1       160        0            22K2         0       0    1
2           2       160        0            22K2         0       0    1
3           3       160        0            22K2         0       0    1
4           4       160        0            22K2         0       0    1

     gross originOfTransportCode                arrivalTime  ...  \
0  27610.0                 CNSHA  2025-04-12 12:43:17+00:00  ...
1  27610.0                 CNSHA  2025-04-12 12:43:17+00:00  ...
2  27610.0                 CNSHA  2025-04-12 12:43:17+00:00  ...
3  27610.0                 CNSHA  2025-04-12 12:43:17+00:00  ...
4  27610.0                 CNSHA  2025-04-12 12:43:17+00:00  ...

  temperature_2m  relative_humidity_2m  precipitation  rain  weather_code  \
0           18.8                    36            0.0   0.0             0
1           18.8                    36            0.0   0.0             0
2           18.8                    36            0.0   0.0             0
3           18.8                    36            0.0   0.0             0
4           18.8                    36            0.0   0.0             0

  cloud_cover wind_speed_10m wind_gusts_10m  is_raining bad_weather_score
0           0            2.6           16.9           0                 0
1           0            2.6           16.9           0                 0
2           0            2.6           16.9           0                 0
3           0            2.6           16.9           0                 0
4           0            2.6           16.9           0                 0

[5 rows x 38 columns]

In [111]:
df = df.drop(columns = ["Unnamed: 0", "snapshot_date", "weather_match_time", "weather_hour"])
print(df.head(5))

   lineCode  iedCode sizetypeIsoCode  typeCode  reefer  teu    gross  \
0       160        0            22K2         0       0    1  27610.0
1       160        0            22K2         0       0    1  27610.0
2       160        0            22K2         0       0    1  27610.0
3       160        0            22K2         0       0    1  27610.0
4       160        0            22K2         0       0    1  27610.0

  originOfTransportCode                arrivalTime arrivalPolCode  ...  \
0                 CNSHA  2025-04-12 12:43:17+00:00          CNSHA  ...
1                 CNSHA  2025-04-12 12:43:17+00:00          CNSHA  ...
2                 CNSHA  2025-04-12 12:43:17+00:00          CNSHA  ...
3                 CNSHA  2025-04-12 12:43:17+00:00          CNSHA  ...
4                 CNSHA  2025-04-12 12:43:17+00:00          CNSHA  ...

   temperature_2m  relative_humidity_2m  precipitation  rain weather_code  \
0            18.8                    36            0.0   0.0            0
1            18.8                    36            0.0   0.0            0
2            18.8                    36            0.0   0.0            0
3            18.8                    36            0.0   0.0            0
4            18.8                    36            0.0   0.0            0

  cloud_cover wind_speed_10m  wind_gusts_10m is_raining bad_weather_score
0           0            2.6            16.9          0                 0
1           0            2.6            16.9          0                 0
2           0            2.6            16.9          0                 0
3           0            2.6            16.9          0                 0
4           0            2.6            16.9          0                 0

[5 rows x 34 columns]

In [ ]:
# df = df[df['departureTime'].notna()]

KeyError: 'departureTime'

In [5]:
# print(len(df))
df["arrivalTime"] = pd.to_datetime(df["arrivalTime"], utc=True)
df["departureTime"] = pd.to_datetime(df["departureTime"], utc=True)

df["dwell_hours"] = (
    df["departureTime"] - df["arrivalTime"]
).dt.total_seconds() / 3600

# drop departureTime
df.drop(columns=["departureTime"], inplace=True)
print(df[["arrivalTime", "dwell_hours"]].head())

KeyError: 'departureTime'

In [119]:
# print(df["dwell_hours"].head(20))
df.to_csv("data/eurogate_train.csv")

In [7]:
df = df.drop(columns = ["originOfTransportCode"])
df.to_csv("data/eurogate_data.csv")

KeyError: "['originOfTransportCode'] not found in axis"

In [8]:
current_row = "sizetypeIsoCode"

null_total = df[current_row].isna().sum()
not_null = df[current_row].notna().sum()
total_rows = null_total+not_null
null_percent = null_total / (total_rows)

print(f"percent null: {null_percent}")

count_1 = df[current_row].value_counts()[0]
print(f"percent first value: {count_1/total_rows}")

count_2 = df[current_row].value_counts()[1]
count_3 = df[current_row].value_counts()[2]
count_4 = df[current_row].value_counts()[3]
count_5 = df[current_row].value_counts()[4]
top_5_count = count_1 + count_2 + count_3 + count_4 + count_5
print(f"percent first five value: {top_5_count/total_rows}")

count_6 = df[current_row].value_counts()[5]
count_7 = df[current_row].value_counts()[6]
count_8 = df[current_row].value_counts()[7]
count_9 = df[current_row].value_counts()[8]
count_10 = df[current_row].value_counts()[9]
top_10_count = count_1 + count_2 + count_3 + count_4 + count_5 + count_6 + count_7 + count_8 + count_9 + count_10
print(f"percent first ten value: {top_10_count/total_rows}")

count_11 = df[current_row].value_counts()[10]
count_12 = df[current_row].value_counts()[11]
count_13 = df[current_row].value_counts()[12]
count_14 = df[current_row].value_counts()[13]
count_15 = df[current_row].value_counts()[14]
count_16 = df[current_row].value_counts()[15]
count_17 = df[current_row].value_counts()[16]
count_18 = df[current_row].value_counts()[17]
count_19 = df[current_row].value_counts()[18]
count_20 = df[current_row].value_counts()[19]

top_20_count = count_1 + count_2 + count_3 + count_4 + count_5 + count_6 + count_7 + count_8 + count_9 + count_10 + count_11 + count_12 + count_13 + count_14 + count_15 + count_16 + count_17 + count_18 + count_19 + count_20
print(f"percent first twenty value: {top_20_count/total_rows}")

percent null: 0.0
percent first value: 0.5668446437365977
percent first five value: 0.9675260443189412

/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_1 = df[current_row].value_counts()[0]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_2 = df[current_row].value_counts()[1]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_3 = df[current_row].value_counts()[2]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_4 = df[current_row].value_counts()[3]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_5 = df[current_row].value_counts()[4]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_6 = df[current_row].value_counts()[5]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_7 = df[current_row].value_counts()[6]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_8 = df[current_row].value_counts()[7]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_9 = df[current_row].value_counts()[8]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:24: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_10 = df[current_row].value_counts()[9]

percent first ten value: 0.981370307174378
percent first twenty value: 0.9952201507061649

/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_11 = df[current_row].value_counts()[10]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:29: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_12 = df[current_row].value_counts()[11]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:30: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_13 = df[current_row].value_counts()[12]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:31: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_14 = df[current_row].value_counts()[13]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:32: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_15 = df[current_row].value_counts()[14]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:33: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_16 = df[current_row].value_counts()[15]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_17 = df[current_row].value_counts()[16]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:35: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_18 = df[current_row].value_counts()[17]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:36: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_19 = df[current_row].value_counts()[18]
/var/folders/rv/q52q8kmj0s558xpyhlshtzw00000gn/T/ipykernel_58648/855293900.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count_20 = df[current_row].value_counts()[19]

In [9]:
import numpy as np
import pandas as pd

# typeCode: 0-10 back to original labels
type_reverse = {
    0: "TK",
    1: "RF",
    2: "DC",
    3: "OT",
    4: "FC",
    5: "DO",
    6: "SR",
    7: "PL",
    8: "AC",
    9: "OH",
    10: "FR",
}

# arrivalType: 0-3 back to labels
arrival_reverse = {
    0: "OCEAN_CARRIER",
    1: "FEEDER",
    2: "SCHUTE",
    3: "BINNEN",
}

# departureType: 1-7 back to labels
departure_reverse = {
    1: "TRUCK",
    2: "RAIL",
    3: "OCEAN_CARRIER",
    4: "INTER_TERMINAL",
    5: "FEEDER",
    6: "SCHUTE",
    7: "BINNEN",
}

# iedCode: 0/1 back to labels
ied_reverse = {
    0: "IMPORT",
    1: "EXPORT",
}

# released: if you encoded Y/N as 1/0
released_reverse = {
    1: "Y",
    0: "N",
}

# Apply safely
df["typeCode"] = df["typeCode"].map(type_reverse)
df["arrivalType"] = df["arrivalType"].map(arrival_reverse)
df["departureType"] = df["departureType"].map(departure_reverse)
df["iedCode"] = df["iedCode"].map(ied_reverse)
df["released"] = df["released"].map(released_reverse)

print(df[["typeCode", "arrivalType", "departureType", "iedCode", "released"]].head())

  typeCode arrivalType departureType iedCode released
0      NaN         NaN           NaN  IMPORT        Y
1      NaN         NaN           NaN  IMPORT        Y
2      NaN         NaN           NaN  IMPORT        Y
3      NaN         NaN           NaN  IMPORT        Y
4      NaN         NaN           NaN  IMPORT        Y

In [11]:
df = pd.read_csv("data/eurogate_train.csv")
print(df[["arrivalType"]].head(5))

     arrivalType
0  OCEAN_CARRIER
1  OCEAN_CARRIER
2  OCEAN_CARRIER
3  OCEAN_CARRIER
4  OCEAN_CARRIER

In [15]:
# df = df.drop(columns=["departureType"])
print(df[["iedCode"]].head(5))

   iedCode
0        0
1        0
2        0
3        0
4        0

In [128]:
df["reefer"] = df["reefer"].astype(int)

df["released"] = df["released"].map({
    "Y": 1,
    "N": 0
})
df["iedCode"] = df["iedCode"].map({
    "IMPORT": 0,
    "EXPORT": 1
})

In [134]:
# print(df[["reefer", "iedCode", "released"]].head(50))
df.to_csv("data/eurogate_train.csv")

In [16]:
# one hot encode the top twenty ISO codes (99.6% of data) and labels the rest as other
# this will add ~ 20 columns to dataset 
top20_iso = df["sizetypeIsoCode"].value_counts().nlargest(20).index

df["sizetypeIsoCode_clean"] = np.where(
    df["sizetypeIsoCode"].isin(top20_iso),
    df["sizetypeIsoCode"],
    "OTHER"
)

df = pd.get_dummies(
    df,
    columns=["sizetypeIsoCode_clean"],
    prefix="iso",
    drop_first=True
)

df = df.drop(columns=["sizetypeIsoCode"])

In [17]:
# break arrival time into hour, day of week, month, weekend, and sin/cos for month/hour 
# -> so it is clear to the model that 12:00 -> 1:00 is 1 hour
df["arrivalTime"] = pd.to_datetime(df["arrivalTime"], errors="coerce", utc=True)

df["arrival_hour"] = df["arrivalTime"].dt.hour
df["arrival_dayofweek"] = df["arrivalTime"].dt.dayofweek
df["arrival_month"] = df["arrivalTime"].dt.month
df["arrival_is_weekend"] = (df["arrival_dayofweek"] >= 5).astype(int)

df["arrival_hour_sin"] = np.sin(2 * np.pi * df["arrival_hour"] / 24)
df["arrival_hour_cos"] = np.cos(2 * np.pi * df["arrival_hour"] / 24)

df["arrival_month_sin"] = np.sin(2 * np.pi * df["arrival_month"] / 12)
df["arrival_month_cos"] = np.cos(2 * np.pi * df["arrival_month"] / 12)

In [18]:
# we only need eta to find "lateness" so make this column and then drop arrival ETA col

df["arrivalVoyageEta"] = pd.to_datetime(df["arrivalVoyageEta"], errors="coerce", utc=True)

df["eta_error_hours"] = (
    df["arrivalTime"] - df["arrivalVoyageEta"]
).dt.total_seconds() / 3600

df = df.drop(columns=["arrivalVoyageEta"])

In [19]:
# dont need arrival time anymore 
df = df.drop(columns=["arrivalTime"])

In [20]:
# too many categories so frequency encode instead for arrival pol code
df["arrivalPolCode"] = df["arrivalPolCode"].fillna("MISSING")

arrival_pol_freq = df["arrivalPolCode"].value_counts(normalize=True)

df["arrivalPolCode_freq"] = df["arrivalPolCode"].map(arrival_pol_freq)

df = df.drop(columns=["arrivalPolCode"])

In [21]:
# also frequency encode for arrival vessel name
df["arrivalVesselName"] = df["arrivalVesselName"].fillna("MISSING")

vessel_freq = df["arrivalVesselName"].value_counts(normalize=True)

df["arrivalVesselName_freq"] = df["arrivalVesselName"].map(vessel_freq)

df = df.drop(columns=["arrivalVesselName"])

In [22]:
# one hot encode the top 41 arrival service names 
# this will add 41 columns to dataset 

df["arrivalServiceName"] = df["arrivalServiceName"].fillna("MISSING")

df = pd.get_dummies(
    df,
    columns=["arrivalServiceName"],
    prefix="service",
    drop_first=True
)

In [23]:
print(df.shape)
print(df.head())
print(df.isna().mean().sort_values(ascending=False).head(20))

(716759, 98)
   Unnamed: 0  lineCode  iedCode typeCode  reefer  teu    gross  \
0           2       160        0       TK       0    1  27610.0
1           3       160        0       TK       0    1  27610.0
2           4       160        0       TK       0    1  27610.0
3           5       160        0       TK       0    1  27610.0
4           6       160        0       TK       0    1  27610.0

     arrivalType  arrivalLocationX  arrivalLocationY  ...  service_NWL-Barge  \
0  OCEAN_CARRIER                23                15  ...              False
1  OCEAN_CARRIER                23                15  ...              False
2  OCEAN_CARRIER                23                15  ...              False
3  OCEAN_CARRIER                23                15  ...              False
4  OCEAN_CARRIER                23                15  ...              False

   service_Norwegen (NORTH SEA CONTAINER LINE)  \
0                                        False
1                                        False
2                                        False
3                                        False
4                                        False

   service_Norwegendienst Westküste  service_PLX POLAND  \
0                             False               False
1                             False               False
2                             False               False
3                             False               False
4                             False               False

   service_RFS FEEDER IE1  service_RFS FEEDER IE2  \
0                   False                   False
1                   False                   False
2                   False                   False
3                   False                   False
4                   False                   False

   service_SBX BALTIC UNIF/CMA/ OOCL  service_SWX 2 SERVICE  \
0                              False                  False
1                              False                  False
2                              False                  False
3                              False                  False
4                              False                  False

   service_WALTER LAUK  service_X-PRESS FEEDER
0                False                   False
1                False                   False
2                False                   False
3                False                   False
4                False                   False

[5 rows x 98 columns]
gross                                                   0.000088
Unnamed: 0                                              0.000000
service_CMA CGM FAL 1                                   0.000000
service_MAERSK E27                                      0.000000
service_MAE EUROSAL/SAWC                                0.000000
service_LEVANTE                                         0.000000
service_IOS - ME 1                                      0.000000
service_HSUD NEO SAMBA SAEC 1                           0.000000
service_FLX FINLAND EXPRESS                             0.000000
service_EUROMAR                                         0.000000
service_Diverse (absolute Ausnahme NUR Hauptschiffe)    0.000000
service_CMA CGM FEMEX                                   0.000000
service_CMA CGM FAL3                                    0.000000
service_CMA CGM EPIC                                    0.000000
service_MSC BRITANNIA                                   0.000000
service_Baltic Sea, etc (UNIFEEDER) FLZ                 0.000000
service_BOERDE                                          0.000000
service_Arctic Container Lines AS                       0.000000
arrivalVesselName_freq                                  0.000000
arrivalPolCode_freq                                     0.000000
dtype: float64

In [24]:
df.to_csv("data/eurogate_train_encoded.csv")

In [25]:
import pandas as pd
import numpy as np

# Show all rows/columns when printing
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

summary_rows = []

for col in df.columns:

    s = df[col]

    row = {
        "column": col,
        "dtype": str(s.dtype),
        "n_rows": len(s),
        "n_missing": s.isna().sum(),
        "pct_missing": round(100 * s.isna().mean(), 3),
        "n_unique": s.nunique(dropna=True),
        "memory_mb": round(s.memory_usage(deep=True) / 1024**2, 4),
    }

    # Most common value info
    vc = s.value_counts(dropna=False)

    if len(vc) > 0:
        row["top_value"] = str(vc.index[0])
        row["top_count"] = int(vc.iloc[0])
        row["top_pct"] = round(100 * vc.iloc[0] / len(s), 3)
    else:
        row["top_value"] = None
        row["top_count"] = None
        row["top_pct"] = None

    # Numeric stats
    if pd.api.types.is_float_dtype(s) or pd.api.types.is_integer_dtype(s):

        row["mean"] = s.mean()
        row["std"] = s.std()
        row["min"] = s.min()
        row["25%"] = s.quantile(0.25)
        row["50%"] = s.quantile(0.50)
        row["75%"] = s.quantile(0.75)
        row["max"] = s.max()

        # Additional useful stats
        row["skew"] = s.skew()
        row["zeros"] = (s == 0).sum()
        row["pct_zeros"] = round(
            100 * (s == 0).sum() / len(s),
            3
        )

    else:
        row["mean"] = None
        row["std"] = None
        row["min"] = None
        row["25%"] = None
        row["50%"] = None
        row["75%"] = None
        row["max"] = None
        row["skew"] = None
        row["zeros"] = None
        row["pct_zeros"] = None

    summary_rows.append(row)

summary = pd.DataFrame(summary_rows)

# Sort by missingness (optional)
summary = summary.sort_values(
    by="pct_missing",
    ascending=False
)

print(summary)

# Save if desired
summary.to_csv(
    "dataset_summary.csv",
    index=False
)

print("\nSaved dataset_summary.csv")

                                                  column    dtype  n_rows  \
6                                                  gross  float64  716759
0                                             Unnamed: 0    int64  716759
62                                 service_CMA CGM FAL 1     bool  716759
72                                    service_MAERSK E27     bool  716759
71                              service_MAE EUROSAL/SAWC     bool  716759
70                                       service_LEVANTE     bool  716759
69                                    service_IOS - ME 1     bool  716759
68                         service_HSUD NEO SAMBA SAEC 1     bool  716759
67                           service_FLX FINLAND EXPRESS     bool  716759
66                                       service_EUROMAR     bool  716759
65  service_Diverse (absolute Ausnahme NUR Hauptschiffe)     bool  716759
64                                 service_CMA CGM FEMEX     bool  716759
63                                  service_CMA CGM FAL3     bool  716759
61                                  service_CMA CGM EPIC     bool  716759
74                                 service_MSC BRITANNIA     bool  716759
60               service_Baltic Sea, etc (UNIFEEDER) FLZ     bool  716759
59                                        service_BOERDE     bool  716759
58                     service_Arctic Container Lines AS     bool  716759
57                                arrivalVesselName_freq  float64  716759
56                                   arrivalPolCode_freq  float64  716759
55                                       eta_error_hours  float64  716759
54                                     arrival_month_cos  float64  716759
53                                     arrival_month_sin  float64  716759
52                                      arrival_hour_cos  float64  716759
73                                  service_MAERSK Extra     bool  716759
75                           service_MSC EQUADOR/ BALTIC     bool  716759
50                                    arrival_is_weekend    int64  716759
87                             service_NEMO / AUSTRALIEN     bool  716759
96                                   service_WALTER LAUK     bool  716759
95                                 service_SWX 2 SERVICE     bool  716759
94                     service_SBX BALTIC UNIF/CMA/ OOCL     bool  716759
93                                service_RFS FEEDER IE2     bool  716759
92                                service_RFS FEEDER IE1     bool  716759
91                                    service_PLX POLAND     bool  716759
90                      service_Norwegendienst Westküste     bool  716759
89           service_Norwegen (NORTH SEA CONTAINER LINE)     bool  716759
88                                     service_NWL-Barge     bool  716759
86                                   service_NE 4 / AE 5     bool  716759
76                             service_MSC GREECE TURKEY     bool  716759
85                                          service_NE 4     bool  716759
84                                    service_NE 2 / AE1     bool  716759
83                                          service_NE 2     bool  716759
82                                service_MSC/ZIM ISRAEL     bool  716759
81                                     service_MSC-EXTRA     bool  716759
80                                      service_MSC SWAN     bool  716759
79                           service_MSC SAF - SÜDAFRIKA     bool  716759
78                               service_MSC NWC to IPAK     bool  716759
77                                      service_MSC IPAK     bool  716759
51                                      arrival_hour_sin  float64  716759
49                                         arrival_month    int32  716759
1                                               lineCode    int64  716759
48                                     arrival_dayofweek    int32  716759
23                                        wind_gusts_10m  float64  716759
22                                        wind_speed_10m  float64  716759
21                                           cloud_cover    int64  716759
20                                          weather_code    int64  716759
19                                                  rain  float64  716759
18                                         precipitation  float64  716759
17                                  relative_humidity_2m    int64  716759
16                                        temperature_2m  float64  716759
15                   numberOfDepartureContainersOnVessel    int64  716759
14               numberOfRemainOnBoardContainersOnVessel    int64  716759
13                     numberOfArrivalContainersOnVessel    int64  716759
12                                              released    int64  716759
11                                    arrivalServiceCode    int64  716759
10                                      arrivalLocationZ    int64  716759
9                                       arrivalLocationY    int64  716759
8                                       arrivalLocationX    int64  716759
7                                            arrivalType   object  716759
5                                                    teu    int64  716759
4                                                 reefer    int64  716759
3                                               typeCode   object  716759
2                                                iedCode    int64  716759
24                                            is_raining    int64  716759
25                                     bad_weather_score    int64  716759
26                                           dwell_hours  float64  716759
38                                              iso_45G0     bool  716759
47                                          arrival_hour    int32  716759
46                                             iso_OTHER     bool  716759
45                                              iso_L5G1     bool  716759
44                                              iso_4EG1     bool  716759
43                                              iso_45U1     bool  716759
42                                              iso_45R5     bool  716759
41                                              iso_45R1     bool  716759
40                                              iso_45P3     bool  716759
39                                              iso_45G1     bool  716759
37                                              iso_42U1     bool  716759
27                                              iso_22GB     bool  716759
36                                              iso_42P3     bool  716759
35                                              iso_42G1     bool  716759
34                                              iso_25G1     bool  716759
33                                              iso_22U1     bool  716759
32                                              iso_22T6     bool  716759
31                                              iso_22T1     bool  716759
30                                              iso_22R1     bool  716759
29                                              iso_22P3     bool  716759
28                                              iso_22K2     bool  716759
97                                service_X-PRESS FEEDER     bool  716759

    n_missing  pct_missing  n_unique  memory_mb             top_value  \
6          63        0.009     25939     5.4686               29100.0
0           0        0.000    716759     5.4686                     2
62          0        0.000         2     0.6837                 False
72          0        0.000         2     0.6837                 False
71          0        0.000         2     0.6837                 False
70          0        0.000         2     0.6837                 False
69          0        0.000         2     0.6837                 False
68          0        0.000         2     0.6837                 False
67          0        0.000         2     0.6837                 False
66          0        0.000         2     0.6837                 False
65          0        0.000         2     0.6837                 False
64          0        0.000         2     0.6837                 False
63          0        0.000         2     0.6837                 False
61          0        0.000         2     0.6837                 False
74          0        0.000         2     0.6837                 False
60          0        0.000         2     0.6837                 False
59          0        0.000         2     0.6837                 False
58          0        0.000         2     0.6837                 False
57          0        0.000       219     5.4686   0.03417048129148012
56          0        0.000       211     5.4686   0.14210494740910123
55          0        0.000     79382     5.4686     3.846111111111111
54          0        0.000        11     5.4686  -0.49999999999999983
53          0        0.000        11     5.4686    0.8660254037844387
52          0        0.000        22     5.4686  -0.25881904510252063
73          0        0.000         2     0.6837                 False
75          0        0.000         2     0.6837                 False
50          0        0.000         2     5.4686                     0
87          0        0.000         2     0.6837                 False
96          0        0.000         2     0.6837                 False
95          0        0.000         2     0.6837                 False
94          0        0.000         2     0.6837                 False
93          0        0.000         2     0.6837                 False
92          0        0.000         2     0.6837                 False
91          0        0.000         2     0.6837                 False
90          0        0.000         2     0.6837                 False
89          0        0.000         2     0.6837                 False
88          0        0.000         2     0.6837                 False
86          0        0.000         2     0.6837                 False
76          0        0.000         2     0.6837                 False
85          0        0.000         2     0.6837                 False
84          0        0.000         2     0.6837                 False
83          0        0.000         2     0.6837                 False
82          0        0.000         2     0.6837                 False
81          0        0.000         2     0.6837                 False
80          0        0.000         2     0.6837                 False
79          0        0.000         2     0.6837                 False
78          0        0.000         2     0.6837                 False
77          0        0.000         2     0.6837                 False
51          0        0.000        22     5.4686   0.49999999999999994
49          0        0.000        12     2.7343                     4
1           0        0.000        19     5.4686                    77
48          0        0.000         7     2.7343                     4
23          0        0.000       159     5.4686                  22.7
22          0        0.000       266     5.4686                   9.2
21          0        0.000       101     5.4686                   100
20          0        0.000        11     5.4686                     3
19          0        0.000        35     5.4686                   0.0
18          0        0.000        36     5.4686                   0.0
17          0        0.000        71     5.4686                    95
16          0        0.000       242     5.4686                   9.1
15          0        0.000       412     5.4686                  1317
14          0        0.000       395     5.4686                  1057
13          0        0.000       385     5.4686                  3480
12          0        0.000         2     5.4686                     1
11          0        0.000        38     5.4686                   219
10          0        0.000        29     5.4686                    82
9           0        0.000        26     5.4686                     1
8           0        0.000        88     5.4686                    54
7           0        0.000         4    41.5523         OCEAN_CARRIER
5           0        0.000         2     5.4686                     2
4           0        0.000         2     5.4686                     0
3           0        0.000        11    34.8614                    DC
2           0        0.000         2     5.4686                     0
24          0        0.000         2     5.4686                     0
25          0        0.000         4     5.4686                     1
26          0        0.000    118029     5.4686    42.844722222222224
38          0        0.000         2     0.6837                 False
47          0        0.000        24     2.7343                    23
46          0        0.000         2     0.6837                 False
45          0        0.000         2     0.6837                 False
44          0        0.000         2     0.6837                 False
43          0        0.000         2     0.6837                 False
42          0        0.000         2     0.6837                 False
41          0        0.000         2     0.6837                 False
40          0        0.000         2     0.6837                 False
39          0        0.000         2     0.6837                  True
37          0        0.000         2     0.6837                 False
27          0        0.000         2     0.6837                 False
36          0        0.000         2     0.6837                 False
35          0        0.000         2     0.6837                 False
34          0        0.000         2     0.6837                 False
33          0        0.000         2     0.6837                 False
32          0        0.000         2     0.6837                 False
31          0        0.000         2     0.6837                 False
30          0        0.000         2     0.6837                 False
29          0        0.000         2     0.6837                 False
28          0        0.000         2     0.6837                 False
97          0        0.000         2     0.6837                 False

    top_count  top_pct           mean            std          min  \
6        1145    0.160   19042.216235    8009.422724  2090.000000
0           1    0.000  570277.203071  327928.195460     2.000000
62     645110   90.004            NaN            NaN          NaN
72     710446   99.119            NaN            NaN          NaN
71     707488   98.707            NaN            NaN          NaN
70     703250   98.115            NaN            NaN          NaN
69     673619   93.981            NaN            NaN          NaN
68     687487   95.916            NaN            NaN          NaN
67     703426   98.140            NaN            NaN          NaN
66     713275   99.514            NaN            NaN          NaN
65     716664   99.987            NaN            NaN          NaN
64     704210   98.249            NaN            NaN          NaN
63     637100   88.886            NaN            NaN          NaN
61     695865   97.085            NaN            NaN          NaN
74     716179   99.919            NaN            NaN          NaN
60     670868   93.597            NaN            NaN          NaN
59     713929   99.605            NaN            NaN          NaN
58     715726   99.856            NaN            NaN          NaN
57      24492    3.417       0.014866       0.010706     0.000001
56     101855   14.210       0.053209       0.048740     0.000001
55         80    0.011      19.869625      16.569122    -3.583056
54     329127   45.919      -0.017240       0.510047    -1.000000
53     329127   45.919       0.314087       0.800566    -1.000000
52      63809    8.902       0.015007       0.717421    -1.000000
73     695752   97.069            NaN            NaN          NaN
75     715207   99.783            NaN            NaN          NaN
50     518009   72.271       0.277290       0.447661     0.000000
87     693287   96.725            NaN            NaN          NaN
96     709138   98.937            NaN            NaN          NaN
95     702680   98.036            NaN            NaN          NaN
94     696604   97.188            NaN            NaN          NaN
93     716250   99.929            NaN            NaN          NaN
92     715205   99.783            NaN            NaN          NaN
91     716535   99.969            NaN            NaN          NaN
90     716663   99.987            NaN            NaN          NaN
89     714930   99.745            NaN            NaN          NaN
88     713575   99.556            NaN            NaN          NaN
86     711825   99.312            NaN            NaN          NaN
76     713647   99.566            NaN            NaN          NaN
85     678673   94.686            NaN            NaN          NaN
84     715104   99.769            NaN            NaN          NaN
83     632672   88.268            NaN            NaN          NaN
82     712370   99.388            NaN            NaN          NaN
81     709696   99.015            NaN            NaN          NaN
80     691939   96.537            NaN            NaN          NaN
79     714718   99.715            NaN            NaN          NaN
78     714599   99.699            NaN            NaN          NaN
77     699618   97.609            NaN            NaN          NaN
51      62462    8.715      -0.018644       0.696229    -1.000000
49     329127   45.919       6.054082       3.179711     1.000000
1      226556   31.608      79.330401      54.186194     1.000000
48     115625   16.132       3.026318       1.968361     0.000000
23      15952    2.226      23.384803      10.747531     1.100000
22      10710    1.494      10.669344       5.151691     0.200000
21     273537   38.163      60.462261      43.400777     0.000000
20     308687   43.067       7.344389      16.032826     0.000000
19     636788   88.843       0.051098       0.246098     0.000000
18     636771   88.840       0.051142       0.246440     0.000000
17      31689    4.421      78.977468      15.762412    24.000000
16      16239    2.266      10.163234       3.995469    -5.600000
15      25455    3.551    1114.290933     718.734408     0.000000
14      24492    3.417    1911.481464    1501.675883     0.000000
13      24492    3.417    1819.669655    1312.409869     1.000000
12     498355   69.529       0.695289       0.460285     0.000000
11      85742   11.962     181.399896      47.501944    32.000000
10      50873    7.098      37.806293      34.852396     1.000000
9       67145    9.368       7.785569       5.626151     0.000000
8       28574    3.987      37.283423      22.770626     1.000000
7      592692   82.691            NaN            NaN          NaN
5      477217   66.580       1.665798       0.471711     1.000000
4      685581   95.650       0.043499       0.203977     0.000000
3      665707   92.877            NaN            NaN          NaN
2      469178   65.458       0.345417       0.475504     0.000000
24     636771   88.840       0.111597       0.314870     0.000000
25     285953   39.895       0.899114       0.860887     0.000000
26         28    0.004     119.532471     112.081870     0.982222
38     714726   99.716            NaN            NaN          NaN
47      39717    5.541      11.703723       7.073767     0.000000
46     713333   99.522            NaN            NaN          NaN
45     715791   99.865            NaN            NaN          NaN
44     716341   99.942            NaN            NaN          NaN
43     715653   99.846            NaN            NaN          NaN
42     715664   99.847            NaN            NaN          NaN
41     687549   95.925            NaN            NaN          NaN
40     714027   99.619            NaN            NaN          NaN

In [ ]:
df= df.drop(columns=[["Unnamed: 0"]])
df = df.dropna(subset=['gross'])
df.to_csv("data/eurogate_train_encoded.csv")

   Unnamed: 0  lineCode  iedCode sizetypeIsoCode typeCode  reefer  teu  \
0           2       160        0            22K2       TK       0    1
1           3       160        0            22K2       TK       0    1
2           4       160        0            22K2       TK       0    1
3           5       160        0            22K2       TK       0    1
4           6       160        0            22K2       TK       0    1

     gross                arrivalTime arrivalPolCode  ...  \
0  27610.0  2025-04-12 12:43:17+00:00          CNSHA  ...
1  27610.0  2025-04-12 12:43:17+00:00          CNSHA  ...
2  27610.0  2025-04-12 12:43:17+00:00          CNSHA  ...
3  27610.0  2025-04-12 12:43:17+00:00          CNSHA  ...
4  27610.0  2025-04-12 12:43:17+00:00          CNSHA  ...

  relative_humidity_2m  precipitation  rain  weather_code cloud_cover  \
0                   36            0.0   0.0             0           0
1                   36            0.0   0.0             0           0
2                   36            0.0   0.0             0           0
3                   36            0.0   0.0             0           0
4                   36            0.0   0.0             0           0

  wind_speed_10m wind_gusts_10m  is_raining  bad_weather_score  dwell_hours
0            2.6           16.9           0                  0    50.946944
1            2.6           16.9           0                  0    50.946944
2            2.6           16.9           0                  0    50.946944
3            2.6           16.9           0                  0    50.946944
4            2.6           16.9           0                  0    50.946944

[5 rows x 34 columns]

In [6]:
print(df["dwell_hours"].head(5))

0    50.946944
1    50.946944
2    50.946944
3    50.946944
4    50.946944
Name: dwell_hours, dtype: float64

In [3]:
df = pd.read_csv("data/eurogate_train_encoded.csv")

In [6]:
print(df.columns.tolist())

['Unnamed: 0.1', 'Unnamed: 0', 'lineCode', 'iedCode', 'typeCode', 'reefer', 'teu', 'gross', 'arrivalType', 'arrivalLocationX', 'arrivalLocationY', 'arrivalLocationZ', 'arrivalServiceCode', 'released', 'numberOfArrivalContainersOnVessel', 'numberOfRemainOnBoardContainersOnVessel', 'numberOfDepartureContainersOnVessel', 'temperature_2m', 'relative_humidity_2m', 'precipitation', 'rain', 'weather_code', 'cloud_cover', 'wind_speed_10m', 'wind_gusts_10m', 'is_raining', 'bad_weather_score', 'dwell_hours', 'iso_22GB', 'iso_22K2', 'iso_22P3', 'iso_22R1', 'iso_22T1', 'iso_22T6', 'iso_22U1', 'iso_25G1', 'iso_42G1', 'iso_42P3', 'iso_42U1', 'iso_45G0', 'iso_45G1', 'iso_45P3', 'iso_45R1', 'iso_45R5', 'iso_45U1', 'iso_4EG1', 'iso_L5G1', 'iso_OTHER', 'arrival_hour', 'arrival_dayofweek', 'arrival_month', 'arrival_is_weekend', 'arrival_hour_sin', 'arrival_hour_cos', 'arrival_month_sin', 'arrival_month_cos', 'eta_error_hours', 'arrivalPolCode_freq', 'arrivalVesselName_freq', 'service_Arctic Container Lines AS', 'service_BOERDE', 'service_Baltic Sea, etc (UNIFEEDER) FLZ', 'service_CMA CGM EPIC', 'service_CMA CGM FAL 1', 'service_CMA CGM FAL3', 'service_CMA CGM FEMEX', 'service_Diverse (absolute Ausnahme NUR Hauptschiffe)', 'service_EUROMAR', 'service_FLX FINLAND EXPRESS', 'service_HSUD NEO SAMBA SAEC 1', 'service_IOS - ME 1', 'service_LEVANTE', 'service_MAE EUROSAL/SAWC', 'service_MAERSK E27', 'service_MAERSK Extra', 'service_MSC BRITANNIA', 'service_MSC EQUADOR/ BALTIC', 'service_MSC GREECE TURKEY', 'service_MSC IPAK', 'service_MSC NWC to IPAK', 'service_MSC SAF - SÜDAFRIKA', 'service_MSC SWAN', 'service_MSC-EXTRA', 'service_MSC/ZIM ISRAEL', 'service_NE 2', 'service_NE 2 / AE1', 'service_NE 4', 'service_NE 4 / AE 5', 'service_NEMO / AUSTRALIEN', 'service_NWL-Barge', 'service_Norwegen (NORTH SEA CONTAINER LINE)', 'service_Norwegendienst Westküste', 'service_PLX POLAND', 'service_RFS FEEDER IE1', 'service_RFS FEEDER IE2', 'service_SBX BALTIC UNIF/CMA/ OOCL', 'service_SWX 2 SERVICE', 'service_WALTER LAUK', 'service_X-PRESS FEEDER']

In [5]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

print(df.head())

   Unnamed: 0.1  Unnamed: 0  lineCode  iedCode typeCode  reefer  teu    gross  \
0             0           2       160        0       TK       0    1  27610.0
1             1           3       160        0       TK       0    1  27610.0
2             2           4       160        0       TK       0    1  27610.0
3             3           5       160        0       TK       0    1  27610.0
4             4           6       160        0       TK       0    1  27610.0

     arrivalType  arrivalLocationX  arrivalLocationY  arrivalLocationZ  \
0  OCEAN_CARRIER                23                15                 8
1  OCEAN_CARRIER                23                15                 8
2  OCEAN_CARRIER                23                15                 8
3  OCEAN_CARRIER                23                15                 8
4  OCEAN_CARRIER                23                15                 8

   arrivalServiceCode  released  numberOfArrivalContainersOnVessel  \
0                 219         1                               3398
1                 219         1                               3398
2                 219         1                               3398
3                 219         1                               3398
4                 219         1                               3398

   numberOfRemainOnBoardContainersOnVessel  \
0                                      899
1                                      899
2                                      899
3                                      899
4                                      899

   numberOfDepartureContainersOnVessel  temperature_2m  relative_humidity_2m  \
0                                 2120            18.8                    36
1                                 2120            18.8                    36
2                                 2121            18.8                    36
3                                 2121            18.8                    36
4                                 2121            18.8                    36

   precipitation  rain  weather_code  cloud_cover  wind_speed_10m  \
0            0.0   0.0             0            0             2.6
1            0.0   0.0             0            0             2.6
2            0.0   0.0             0            0             2.6
3            0.0   0.0             0            0             2.6
4            0.0   0.0             0            0             2.6

   wind_gusts_10m  is_raining  bad_weather_score  dwell_hours  iso_22GB  \
0            16.9           0                  0    50.946944     False
1            16.9           0                  0    50.946944     False
2            16.9           0                  0    50.946944     False
3            16.9           0                  0    50.946944     False
4            16.9           0                  0    50.946944     False

   iso_22K2  iso_22P3  iso_22R1  iso_22T1  iso_22T6  iso_22U1  iso_25G1  \
0      True     False     False     False     False     False     False
1      True     False     False     False     False     False     False
2      True     False     False     False     False     False     False
3      True     False     False     False     False     False     False
4      True     False     False     False     False     False     False

   iso_42G1  iso_42P3  iso_42U1  iso_45G0  iso_45G1  iso_45P3  iso_45R1  \
0     False     False     False     False     False     False     False
1     False     False     False     False     False     False     False
2     False     False     False     False     False     False     False
3     False     False     False     False     False     False     False
4     False     False     False     False     False     False     False

   iso_45R5  iso_45U1  iso_4EG1  iso_L5G1  iso_OTHER  arrival_hour  \
0     False     False     False     False      False            12
1     False     False     False     False      False            12
2     False     False     False     False      False            12
3     False     False     False     False      False            12
4     False     False     False     False      False            12

   arrival_dayofweek  arrival_month  arrival_is_weekend  arrival_hour_sin  \
0                  5              4                   1      1.224647e-16
1                  5              4                   1      1.224647e-16
2                  5              4                   1      1.224647e-16
3                  5              4                   1      1.224647e-16
4                  5              4                   1      1.224647e-16

   arrival_hour_cos  arrival_month_sin  arrival_month_cos  eta_error_hours  \
0              -1.0           0.866025               -0.5        45.721389
1              -1.0           0.866025               -0.5        45.721389
2              -1.0           0.866025               -0.5        45.721389
3              -1.0           0.866025               -0.5        45.721389
4              -1.0           0.866025               -0.5        45.721389

   arrivalPolCode_freq  arrivalVesselName_freq  \
0             0.142105                0.032369
1             0.142105                0.032369
2             0.142105                0.032369
3             0.142105                0.032369
4             0.142105                0.032369

   service_Arctic Container Lines AS  service_BOERDE  \
0                              False           False
1                              False           False
2                              False           False
3                              False           False
4                              False           False

   service_Baltic Sea, etc (UNIFEEDER) FLZ  service_CMA CGM EPIC  \
0                                    False                 False
1                                    False                 False
2                                    False                 False
3                                    False                 False
4                                    False                 False

   service_CMA CGM FAL 1  service_CMA CGM FAL3  service_CMA CGM FEMEX  \
0                  False                 False                  False
1                  False                 False                  False
2                  False                 False                  False
3                  False                 False                  False
4                  False                 False                  False

   service_Diverse (absolute Ausnahme NUR Hauptschiffe)  service_EUROMAR  \
0                                              False               False
1                                              False               False
2                                              False               False
3                                              False               False
4                                              False               False

   service_FLX FINLAND EXPRESS  service_HSUD NEO SAMBA SAEC 1  \
0                        False                          False
1                        False                          False
2                        False                          False
3                        False                          False
4                        False                          False

   service_IOS - ME 1  service_LEVANTE  service_MAE EUROSAL/SAWC  \
0               False            False                     False
1               False            False                     False
2               False            False                     False
3               False            False                     False
4               False            False                     False

   service_MAERSK E27  service_MAERSK Extra  service_MSC BRITANNIA  \
0               False                 False                  False
1               False                 False                  False
2               False                 False                  False
3               False                 False                  False
4               False                 False                  False

   service_MSC EQUADOR/ BALTIC  service_MSC GREECE TURKEY  service_MSC IPAK  \
0                        False                      False             False
1                        False                      False             False
2                        False                      False             False
3                        False                      False             False
4                        False                      False             False

   service_MSC NWC to IPAK  service_MSC SAF - SÜDAFRIKA  service_MSC SWAN  \
0                    False                        False             False
1                    False                        False             False
2                    False                        False             False
3                    False                        False             False
4                    False                        False             False

   service_MSC-EXTRA  service_MSC/ZIM ISRAEL  service_NE 2  \
0              False                   False          True
1              False                   False          True
2              False                   False          True
3              False                   False          True
4              False                   False          True

   service_NE 2 / AE1  service_NE 4  service_NE 4 / AE 5  \
0               False         False                False
1               False         False                False
2               False         False                False
3               False         False                False
4               False         False                False

   service_NEMO / AUSTRALIEN  service_NWL-Barge  \
0                      False              False
1                      False              False
2                      False              False
3                      False              False
4                      False              False

   service_Norwegen (NORTH SEA CONTAINER LINE)  \
0                                        False
1                                        False
2                                        False
3                                        False
4                                        False

   service_Norwegendienst Westküste  service_PLX POLAND  \
0                             False               False
1                             False               False
2                             False               False
3                             False               False
4                             False               False

   service_RFS FEEDER IE1  service_RFS FEEDER IE2  \
0                   False                   False
1                   False                   False
2                   False                   False
3                   False                   False
4                   False                   False

   service_SBX BALTIC UNIF/CMA/ OOCL  service_SWX 2 SERVICE  \
0                              False                  False
1                              False                  False
2                              False                  False
3                              False                  False
4                              False                  False

   service_WALTER LAUK  service_X-PRESS FEEDER
0                False                   False
1                False                   False
2                False                   False
3                False                   False
4                False                   False

In [30]:
# unique_set = set(df['released'])
# print((unique_set))

print(df[["arrivalPolCode_freq"]].head(20))

# print()

    arrivalPolCode_freq
0              0.142105
1              0.142105
2              0.142105
3              0.142105
4              0.142105
5              0.142105
6              0.142105
7              0.006652
8              0.006652
9              0.006652
10             0.006652
11             0.006652
12             0.006652
13             0.006652
14             0.006652
15             0.006652
16             0.006652
17             0.006652
18             0.006652
19             0.006652

## FINAL CLEANING - EUROGATE TRAIN ENCODED

In [31]:
df = pd.read_csv("data/eurogate_train_encoded.csv")

In [33]:
# get all column names from df
print(df.columns.tolist())

['Unnamed: 0.1', 'Unnamed: 0', 'lineCode', 'iedCode', 'typeCode', 'reefer', 'teu', 'gross', 'arrivalType', 'arrivalLocationX', 'arrivalLocationY', 'arrivalLocationZ', 'arrivalServiceCode', 'released', 'numberOfArrivalContainersOnVessel', 'numberOfRemainOnBoardContainersOnVessel', 'numberOfDepartureContainersOnVessel', 'temperature_2m', 'relative_humidity_2m', 'precipitation', 'rain', 'weather_code', 'cloud_cover', 'wind_speed_10m', 'wind_gusts_10m', 'is_raining', 'bad_weather_score', 'dwell_hours', 'iso_22GB', 'iso_22K2', 'iso_22P3', 'iso_22R1', 'iso_22T1', 'iso_22T6', 'iso_22U1', 'iso_25G1', 'iso_42G1', 'iso_42P3', 'iso_42U1', 'iso_45G0', 'iso_45G1', 'iso_45P3', 'iso_45R1', 'iso_45R5', 'iso_45U1', 'iso_4EG1', 'iso_L5G1', 'iso_OTHER', 'arrival_hour', 'arrival_dayofweek', 'arrival_month', 'arrival_is_weekend', 'arrival_hour_sin', 'arrival_hour_cos', 'arrival_month_sin', 'arrival_month_cos', 'eta_error_hours', 'arrivalPolCode_freq', 'arrivalVesselName_freq', 'service_Arctic Container Lines AS', 'service_BOERDE', 'service_Baltic Sea, etc (UNIFEEDER) FLZ', 'service_CMA CGM EPIC', 'service_CMA CGM FAL 1', 'service_CMA CGM FAL3', 'service_CMA CGM FEMEX', 'service_Diverse (absolute Ausnahme NUR Hauptschiffe)', 'service_EUROMAR', 'service_FLX FINLAND EXPRESS', 'service_HSUD NEO SAMBA SAEC 1', 'service_IOS - ME 1', 'service_LEVANTE', 'service_MAE EUROSAL/SAWC', 'service_MAERSK E27', 'service_MAERSK Extra', 'service_MSC BRITANNIA', 'service_MSC EQUADOR/ BALTIC', 'service_MSC GREECE TURKEY', 'service_MSC IPAK', 'service_MSC NWC to IPAK', 'service_MSC SAF - SÜDAFRIKA', 'service_MSC SWAN', 'service_MSC-EXTRA', 'service_MSC/ZIM ISRAEL', 'service_NE 2', 'service_NE 2 / AE1', 'service_NE 4', 'service_NE 4 / AE 5', 'service_NEMO / AUSTRALIEN', 'service_NWL-Barge', 'service_Norwegen (NORTH SEA CONTAINER LINE)', 'service_Norwegendienst Westküste', 'service_PLX POLAND', 'service_RFS FEEDER IE1', 'service_RFS FEEDER IE2', 'service_SBX BALTIC UNIF/CMA/ OOCL', 'service_SWX 2 SERVICE', 'service_WALTER LAUK', 'service_X-PRESS FEEDER']

In [35]:
# drop columns: 'Unnamed: 0.1', 'Unnamed: 0' from df
df = df.drop(columns=["Unnamed: 0.1", "Unnamed: 0"])

In [46]:
# print true if there are any nan values in df
print(df.isna().any().any())
# make a list of columns that have nan values
nan_columns = df.columns[df.isna().any()].tolist()
print(f"Columns with NaN values: {nan_columns}")
# print what percentage of rows have nan values in gross column
print(f"Percentage of rows with NaN values in gross column: {df['gross'].isna().mean() * 100:.2f}%")
# drop rows where gross is nan
df = df.dropna(subset=["gross"])

True
Columns with NaN values: ['gross']
Percentage of rows with NaN values in gross column: 0.01%

In [47]:
print(df.isna().any().any())

False

In [48]:
# one hot encode lineCode with Categorical: [160, 8, 77, 68, 28, 32, 91, 70, 27, 67, 167, 163, 1, 42, 322, 33, 196, 64, 161]
linecode_top = [160, 8, 77, 68, 28, 32, 91, 70, 27, 67, 167, 163, 1, 42, 322, 33, 196, 64, 161]
df["lineCode"] = df["lineCode"].where(df["lineCode"].isin(linecode_top), other="OTHER")
df = pd.get_dummies(df, columns=["lineCode"], prefix="line", drop_first=True)
print(df.columns.tolist())

['iedCode', 'typeCode', 'reefer', 'teu', 'gross', 'arrivalType', 'arrivalLocationX', 'arrivalLocationY', 'arrivalLocationZ', 'arrivalServiceCode', 'released', 'numberOfArrivalContainersOnVessel', 'numberOfRemainOnBoardContainersOnVessel', 'numberOfDepartureContainersOnVessel', 'temperature_2m', 'relative_humidity_2m', 'precipitation', 'rain', 'weather_code', 'cloud_cover', 'wind_speed_10m', 'wind_gusts_10m', 'is_raining', 'bad_weather_score', 'dwell_hours', 'iso_22GB', 'iso_22K2', 'iso_22P3', 'iso_22R1', 'iso_22T1', 'iso_22T6', 'iso_22U1', 'iso_25G1', 'iso_42G1', 'iso_42P3', 'iso_42U1', 'iso_45G0', 'iso_45G1', 'iso_45P3', 'iso_45R1', 'iso_45R5', 'iso_45U1', 'iso_4EG1', 'iso_L5G1', 'iso_OTHER', 'arrival_hour', 'arrival_dayofweek', 'arrival_month', 'arrival_is_weekend', 'arrival_hour_sin', 'arrival_hour_cos', 'arrival_month_sin', 'arrival_month_cos', 'eta_error_hours', 'arrivalPolCode_freq', 'arrivalVesselName_freq', 'service_Arctic Container Lines AS', 'service_BOERDE', 'service_Baltic Sea, etc (UNIFEEDER) FLZ', 'service_CMA CGM EPIC', 'service_CMA CGM FAL 1', 'service_CMA CGM FAL3', 'service_CMA CGM FEMEX', 'service_Diverse (absolute Ausnahme NUR Hauptschiffe)', 'service_EUROMAR', 'service_FLX FINLAND EXPRESS', 'service_HSUD NEO SAMBA SAEC 1', 'service_IOS - ME 1', 'service_LEVANTE', 'service_MAE EUROSAL/SAWC', 'service_MAERSK E27', 'service_MAERSK Extra', 'service_MSC BRITANNIA', 'service_MSC EQUADOR/ BALTIC', 'service_MSC GREECE TURKEY', 'service_MSC IPAK', 'service_MSC NWC to IPAK', 'service_MSC SAF - SÜDAFRIKA', 'service_MSC SWAN', 'service_MSC-EXTRA', 'service_MSC/ZIM ISRAEL', 'service_NE 2', 'service_NE 2 / AE1', 'service_NE 4', 'service_NE 4 / AE 5', 'service_NEMO / AUSTRALIEN', 'service_NWL-Barge', 'service_Norwegen (NORTH SEA CONTAINER LINE)', 'service_Norwegendienst Westküste', 'service_PLX POLAND', 'service_RFS FEEDER IE1', 'service_RFS FEEDER IE2', 'service_SBX BALTIC UNIF/CMA/ OOCL', 'service_SWX 2 SERVICE', 'service_WALTER LAUK', 'service_X-PRESS FEEDER', 'line_8', 'line_27', 'line_28', 'line_32', 'line_33', 'line_42', 'line_64', 'line_67', 'line_68', 'line_70', 'line_77', 'line_91', 'line_160', 'line_161', 'line_163', 'line_167', 'line_196', 'line_322']

In [49]:
df.to_csv("data/eurogate_train_encoded.csv", index=False)

In [55]:
df = pd.read_csv("data/eurogate_train_encoded.csv")

In [59]:
# One-hot encode arrivalType

df = pd.get_dummies(
    df,
    columns=["arrivalType"],
    prefix="arrivalType",
    drop_first=False
)

# Convert True/False dummy columns to 0/1 integers
dummy_cols = [c for c in df.columns if c.startswith("arrivalType_")]
df[dummy_cols] = df[dummy_cols].astype(int)

print(df[dummy_cols].head())

   arrivalType_BINNEN  arrivalType_FEEDER  arrivalType_OCEAN_CARRIER  \
0                   0                   0                          1
1                   0                   0                          1
2                   0                   0                          1
3                   0                   0                          1
4                   0                   0                          1

   arrivalType_SCHUTE
0                   0
1                   0
2                   0
3                   0
4                   0

In [61]:
print(df[["arrivalType_FEEDER", "arrivalType_OCEAN_CARRIER", "arrivalType_SCHUTE", "arrivalType_BINNEN"]].head(20))

    arrivalType_FEEDER  arrivalType_OCEAN_CARRIER  arrivalType_SCHUTE  \
0                    0                          1                   0
1                    0                          1                   0
2                    0                          1                   0
3                    0                          1                   0
4                    0                          1                   0
5                    0                          1                   0
6                    0                          1                   0
7                    0                          1                   0
8                    0                          1                   0
9                    0                          1                   0
10                   0                          1                   0
11                   0                          1                   0
12                   0                          1                   0
13                   0                          1                   0
14                   0                          1                   0
15                   0                          1                   0
16                   0                          1                   0
17                   0                          1                   0
18                   0                          1                   0
19                   0                          1                   0

    arrivalType_BINNEN
0                    0
1                    0
2                    0
3                    0
4                    0
5                    0
6                    0
7                    0
8                    0
9                    0
10                   0
11                   0
12                   0
13                   0
14                   0
15                   0
16                   0
17                   0
18                   0
19                   0

In [62]:
df.to_csv("data/eurogate_train_encoded.csv", index=False)

In [63]:
freq = df["arrivalServiceCode"].value_counts(normalize=True)
df["arrivalServiceCode_freq"] = df["arrivalServiceCode"].map(freq)
df.drop(columns=["arrivalServiceCode"], inplace=True)

In [65]:
print(df[["arrivalServiceCode_freq"]])

        arrivalServiceCode_freq
0                      0.119635
1                      0.119635
2                      0.119635
3                      0.119635
4                      0.119635
...                         ...
716691                 0.006124
716692                 0.006124
716693                 0.006124
716694                 0.006124
716695                 0.006124

[716696 rows x 1 columns]

In [66]:
df.to_csv("data/eurogate_train_encoded.csv", index=False)

In [76]:
df.head()

,iedCode,reefer,teu,gross,arrivalLocationX,arrivalLocationY,arrivalLocationZ,released,numberOfArrivalContainersOnVessel,numberOfRemainOnBoardContainersOnVessel,numberOfDepartureContainersOnVessel,temperature_2m,relative_humidity_2m,precipitation,rain,weather_code,cloud_cover,wind_speed_10m,wind_gusts_10m,is_raining,bad_weather_score,dwell_hours,iso_22GB,iso_22K2,iso_22P3,iso_22R1,iso_22T1,iso_22T6,iso_22U1,iso_25G1,iso_42G1,iso_42P3,iso_42U1,iso_45G0,iso_45G1,iso_45P3,iso_45R1,iso_45R5,iso_45U1,iso_4EG1,iso_L5G1,iso_OTHER,arrival_hour,arrival_dayofweek,arrival_month,arrival_is_weekend,arrival_hour_sin,arrival_hour_cos,arrival_month_sin,arrival_month_cos,eta_error_hours,arrivalPolCode_freq,arrivalVesselName_freq,service_Arctic Container Lines AS,service_BOERDE,"service_Baltic Sea, etc (UNIFEEDER) FLZ",service_CMA CGM EPIC,service_CMA CGM FAL 1,service_CMA CGM FAL3,service_CMA CGM FEMEX,service_Diverse (absolute Ausnahme NUR Hauptschiffe),service_EUROMAR,service_FLX FINLAND EXPRESS,service_HSUD NEO SAMBA SAEC 1,service_IOS - ME 1,service_LEVANTE,service_MAE EUROSAL/SAWC,service_MAERSK E27,service_MAERSK Extra,service_MSC BRITANNIA,service_MSC EQUADOR/ BALTIC,service_MSC GREECE TURKEY,service_MSC IPAK,service_MSC NWC to IPAK,service_MSC SAF - SÜDAFRIKA,service_MSC SWAN,service_MSC-EXTRA,service_MSC/ZIM ISRAEL,service_NE 2,service_NE 2 / AE1,service_NE 4,service_NE 4 / AE 5,service_NEMO / AUSTRALIEN,service_NWL-Barge,service_Norwegen (NORTH SEA CONTAINER LINE),service_Norwegendienst Westküste,service_PLX POLAND,service_RFS FEEDER IE1,service_RFS FEEDER IE2,service_SBX BALTIC UNIF/CMA/ OOCL,service_SWX 2 SERVICE,service_WALTER LAUK,service_X-PRESS FEEDER,line_8,line_27,line_28,line_32,line_33,line_42,line_64,line_67,line_68,line_70,line_77,line_91,line_160,line_161,line_163,line_167,line_196,line_322,arrivalType_BINNEN,arrivalType_FEEDER,arrivalType_OCEAN_CARRIER,arrivalType_SCHUTE,arrivalServiceCode_freq,type_AC,type_DC,type_DO,type_FC,type_FR,type_OH,type_OT,type_PL,type_RF,type_SR,type_TK
0,0,0,1,27610.0,23,15,8,1,3398,899,2120,18.8,36,0.0,0.0,0,0,2.6,16.9,0,0,50.946944,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,5,4,1,1.224647e-16,-1.0,0.866025,-0.5,45.721389,0.142105,0.032369,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0.119635,0,0,0,0,0,0,0,0,0,0,1
1,0,0,1,27610.0,23,15,8,1,3398,899,2120,18.8,36,0.0,0.0,0,0,2.6,16.9,0,0,50.946944,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,5,4,1,1.224647e-16,-1.0,0.866025,-0.5,45.721389,0.142105,0.032369,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0.119635,0,0,0,0,0,0,0,0,0,0,1
2,0,0,1,27610.0,23,15,8,1,3398,899,2121,18.8,36,0.0,0.0,0,0,2.6,16.9,0,0,50.946944,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,5,4,1,1.224647e-16,-1.0,0.866025,-0.5,45.721389,0.142105,0.032369,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0.119635,0,0,0,0,0,0,0,0,0,0,1
3,0,0,1,27610.0,23,15,8,1,3398,899,2121,18.8,36,0.0,0.0,0,0,2.6,16.9,0,0,50.946944,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,5,4,1,1.224647e-16,-1.0,0.866025,-0.5,45.721389,0.142105,0.032369,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0.119635,0,0,0,0,0,0,0,0,0,0,1
4,0,0,1,27610.0,23,15,8,1,3398,899,2121,18.8,36,0.0,0.0,0,0,2.6,16.9,0,0,50.946944,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,5,4,1,1.224647e-16,-1.0,0.866025,-0.5,45.721389,0.142105,0.032369,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0.119635,0,0,0,0,0,0,0,0,0,0,1

In [69]:
# print all unique values in typeCode column
print(df["typeCode"].unique())

['TK' 'RF' 'DC' 'OT' 'FC' 'DO' 'SR' 'PL' 'AC' 'OH' 'FR']

In [70]:
df.to_csv("data/eurogate_train_encoded.csv", index=False)

In [71]:
# one hot encode typeCode values: ['TK' 'RF' 'DC' 'OT' 'FC' 'DO' 'SR' 'PL' 'AC' 'OH' 'FR'] using 1 and 0
type_dummies = pd.get_dummies(df["typeCode"], prefix="type")
df = pd.concat([df, type_dummies], axis=1)
df.drop(columns=["typeCode"], inplace=True)
print(df.filter(like="type_").head())

   type_AC  type_DC  type_DO  type_FC  type_FR  type_OH  type_OT  type_PL  \
0    False    False    False    False    False    False    False    False
1    False    False    False    False    False    False    False    False
2    False    False    False    False    False    False    False    False
3    False    False    False    False    False    False    False    False
4    False    False    False    False    False    False    False    False

   type_RF  type_SR  type_TK
0    False    False     True
1    False    False     True
2    False    False     True
3    False    False     True
4    False    False     True

In [72]:
# for each column that starts with type_, replace True with 1 and False with 0
type_cols = [c for c in df.columns if c.startswith("type_")]
df[type_cols] = df[type_cols].astype(int)
print(df[type_cols].head())

   type_AC  type_DC  type_DO  type_FC  type_FR  type_OH  type_OT  type_PL  \
0        0        0        0        0        0        0        0        0
1        0        0        0        0        0        0        0        0
2        0        0        0        0        0        0        0        0
3        0        0        0        0        0        0        0        0
4        0        0        0        0        0        0        0        0

   type_RF  type_SR  type_TK
0        0        0        1
1        0        0        1
2        0        0        1
3        0        0        1
4        0        0        1

In [75]:
# for each column that starts with line_, replace True with 1 and False with 0
line_cols = [c for c in df.columns if c.startswith("line_")]
df[line_cols] = df[line_cols].astype(int)
print(df[line_cols].head())

   line_8  line_27  line_28  line_32  line_33  line_42  line_64  line_67  \
0       0        0        0        0        0        0        0        0
1       0        0        0        0        0        0        0        0
2       0        0        0        0        0        0        0        0
3       0        0        0        0        0        0        0        0
4       0        0        0        0        0        0        0        0

   line_68  line_70  line_77  line_91  line_160  line_161  line_163  line_167  \
0        0        0        0        0         1         0         0         0
1        0        0        0        0         1         0         0         0
2        0        0        0        0         1         0         0         0
3        0        0        0        0         1         0         0         0
4        0        0        0        0         1         0         0         0

   line_196  line_322
0         0         0
1         0         0
2         0         0
3         0         0
4         0         0

In [77]:
df.to_csv("data/eurogate_train_encoded.csv", index=False)

## GET SNAPSHOT TIMES & ADD REMAINING DWELL

In [78]:
df_original = pd.read_csv("data/eurogate_all_snapshots.csv")
# drop rows where departure time is nan
df_original = df_original.dropna(subset=["departureTime"])
# drop rows where gross is nan
df_original = df_original.dropna(subset=["gross"])
# count number of rows in df_original
print(f"Number of rows in original df: {len(df_original)}")
# count number of rows in df
print(f"Number of rows in cleaned df: {len(df)}")

Number of rows in original df: 716696
Number of rows in cleaned df: 716696

In [82]:
# get the snapshot time from df_original and convert to datetime
# the snapshot time is from the source_file column, for example Containerdaten-2025-04-13_01.56.13.csv is from snapshot time 2025-04-13 01:56:13
df_original["snapshot_time"] = (
    df_original["source_file"]
    .str.extract(r"Containerdaten-(\d{4}-\d{2}-\d{2}_\d{2}\.\d{2}\.\d{2})")[0]
    .str.replace("_", " ", regex=False)
    .str.replace(".", ":", regex=False)
)

df_original["snapshot_time"] = pd.to_datetime(
    df_original["snapshot_time"],
    format="%Y-%m-%d %H:%M:%S"
)

print(df_original[["source_file", "snapshot_time"]].head())

                              source_file       snapshot_time
2  Containerdaten-2025-04-15_01.55.44.csv 2025-04-15 01:55:44
3  Containerdaten-2025-04-16_01.55.44.csv 2025-04-16 01:55:44
4  Containerdaten-2025-04-17_01.55.30.csv 2025-04-17 01:55:30
5  Containerdaten-2025-04-18_01.56.33.csv 2025-04-18 01:56:33
6  Containerdaten-2025-04-19_01.55.40.csv 2025-04-19 01:55:40

In [83]:
# Make sure these are datetime
df_original["snapshot_time"] = pd.to_datetime(
    df_original["snapshot_time"],
    errors="coerce"
)

df_original["departureTime"] = pd.to_datetime(
    df_original["departureTime"],
    errors="coerce",
    utc=True
)

# If snapshot_time is timezone-naive, make departureTime timezone-naive too
df_original["departureTime"] = df_original["departureTime"].dt.tz_localize(None)

# Create snapshot time components
df_original["snapshot_date"] = df_original["snapshot_time"].dt.date
df_original["snapshot_hour"] = df_original["snapshot_time"].dt.hour
df_original["snapshot_minute"] = df_original["snapshot_time"].dt.minute
df_original["snapshot_second"] = df_original["snapshot_time"].dt.second

# Remaining dwell time in decimal hours
df_original["remaining_dwell_hours"] = (
    df_original["departureTime"] - df_original["snapshot_time"]
).dt.total_seconds() / 3600

# Optional: if negative values happen, set them to 0
df_original["remaining_dwell_hours"] = df_original["remaining_dwell_hours"].clip(lower=0)

print(
    df_original[
        [
            "snapshot_time",
            "snapshot_date",
            "snapshot_hour",
            "snapshot_minute",
            "snapshot_second",
            "departureTime",
            "remaining_dwell_hours"
        ]
    ].head()
)

        snapshot_time snapshot_date  snapshot_hour  snapshot_minute  \
2 2025-04-15 01:55:44    2025-04-15              1               55
3 2025-04-16 01:55:44    2025-04-16              1               55
4 2025-04-17 01:55:30    2025-04-17              1               55
5 2025-04-18 01:56:33    2025-04-18              1               56
6 2025-04-19 01:55:40    2025-04-19              1               55

   snapshot_second       departureTime  remaining_dwell_hours
2               44 2025-04-14 15:40:06                    0.0
3               44 2025-04-14 15:40:06                    0.0
4               30 2025-04-14 15:40:06                    0.0
5               33 2025-04-14 15:40:06                    0.0
6               40 2025-04-14 15:40:06                    0.0

In [99]:
# Arrival year
# df_original["arrival_year"] = df_original["arrivalTime"].dt.year
# Snapshot year
# df_original["snapshot_year"] = df_original["snapshot_time"].dt.year

# print(df_original[["arrival_year", "snapshot_year"]].head())

In [ ]:
# print just the year from arrival time for the first row (arrivalTime is an object)
# print((df_original["arrivalTime"].iloc[0][:4]))

2025

In [100]:
# print arrivalTime and snapshot_time for the first row
print(df_original[["arrivalTime", "snapshot_time"]].head(5))

                 arrivalTime       snapshot_time
2  2025-04-12 12:43:17+00:00 2025-04-15 01:55:44
3  2025-04-12 12:43:17+00:00 2025-04-16 01:55:44
4  2025-04-12 12:43:17+00:00 2025-04-17 01:55:30
5  2025-04-12 12:43:17+00:00 2025-04-18 01:56:33
6  2025-04-12 12:43:17+00:00 2025-04-19 01:55:40

In [103]:
df_original["arrivalTime"] = pd.to_datetime(df_original["arrivalTime"])
df_original["snapshot_time"] = pd.to_datetime(df_original["snapshot_time"])
df_original["arrival_year"] = df_original["arrivalTime"].dt.year
df_original["snapshot_year"] = df_original["snapshot_time"].dt.year

print(
    df_original[
        [
            "arrivalTime",
            "arrival_year",
            "snapshot_time",
            "snapshot_year"
        ]
    ].head()
)

                arrivalTime  arrival_year       snapshot_time  snapshot_year
2 2025-04-12 12:43:17+00:00          2025 2025-04-15 01:55:44           2025
3 2025-04-12 12:43:17+00:00          2025 2025-04-16 01:55:44           2025
4 2025-04-12 12:43:17+00:00          2025 2025-04-17 01:55:30           2025
5 2025-04-12 12:43:17+00:00          2025 2025-04-18 01:56:33           2025
6 2025-04-12 12:43:17+00:00          2025 2025-04-19 01:55:40           2025

In [106]:
# how many NaN values are in arrivalTime and snapshot_time
print(f"Number of NaN in arrivalTime: {df_original['arrivalTime'].isna().sum()}")
print(f"Number of NaN in snapshot_time: {df_original['snapshot_time'].isna().sum()}")

Number of NaN in arrivalTime: 0
Number of NaN in snapshot_time: 0

In [107]:
df = pd.read_csv("data/eurogate_train_encoded.csv")

In [108]:
print(f"Number of NaN in arrivalTime: {df_original['arrivalTime'].isna().sum()}")
print(f"Number of NaN in snapshot_time: {df_original['snapshot_time'].isna().sum()}")
print(f"Number of NaN in arrival_year: {df_original['arrival_year'].isna().sum()}")
print(f"Number of NaN in snapshot_year: {df_original['snapshot_year'].isna().sum()}")
print(f"Number of NaN in snapshot_date: {df_original['snapshot_date'].isna().sum()}")
print(f"Number of NaN in snapshot_hour: {df_original['snapshot_hour'].isna().sum()}")
print(f"Number of NaN in snapshot_minute: {df_original['snapshot_minute'].isna().sum()}")
print(f"Number of NaN in snapshot_second: {df_original['snapshot_second'].isna().sum()}")
print(f"Number of NaN in departureTime: {df_original['departureTime'].isna().sum()}")
print(f"Number of NaN in remaining_dwell_hours: {df_original['remaining_dwell_hours'].isna().sum()}")

Number of NaN in arrivalTime: 0
Number of NaN in snapshot_time: 0
Number of NaN in arrival_year: 0
Number of NaN in snapshot_year: 0
Number of NaN in snapshot_date: 0
Number of NaN in snapshot_hour: 0
Number of NaN in snapshot_minute: 0
Number of NaN in snapshot_second: 0
Number of NaN in departureTime: 0
Number of NaN in remaining_dwell_hours: 0

In [109]:
# number of rows in df_original vs num rows in df
print(f"Number of rows in original df: {len(df_original)}")
print(f"Number of rows in cleaned df: {len(df)}")

Number of rows in original df: 716696
Number of rows in cleaned df: 716696

In [111]:
cols_to_add = [
    "arrivalTime",
    "snapshot_time",
    "arrival_year",
    "snapshot_year",
    "snapshot_date",
    "snapshot_hour",
    "snapshot_minute",
    "snapshot_second",
    "departureTime",
    "remaining_dwell_hours"
]

df = df.reset_index(drop=True)
df_original = df_original.reset_index(drop=True)

df[cols_to_add] = df_original[cols_to_add]

print(df[cols_to_add].head())

                arrivalTime       snapshot_time  arrival_year  snapshot_year  \
0 2025-04-12 12:43:17+00:00 2025-04-15 01:55:44          2025           2025
1 2025-04-12 12:43:17+00:00 2025-04-16 01:55:44          2025           2025
2 2025-04-12 12:43:17+00:00 2025-04-17 01:55:30          2025           2025
3 2025-04-12 12:43:17+00:00 2025-04-18 01:56:33          2025           2025
4 2025-04-12 12:43:17+00:00 2025-04-19 01:55:40          2025           2025

  snapshot_date  snapshot_hour  snapshot_minute  snapshot_second  \
0    2025-04-15              1               55               44
1    2025-04-16              1               55               44
2    2025-04-17              1               55               30
3    2025-04-18              1               56               33
4    2025-04-19              1               55               40

        departureTime  remaining_dwell_hours
0 2025-04-14 15:40:06                    0.0
1 2025-04-14 15:40:06                    0.0
2 2025-04-14 15:40:06                    0.0
3 2025-04-14 15:40:06                    0.0
4 2025-04-14 15:40:06                    0.0

In [112]:
print(df[cols_to_add].isna().sum())

arrivalTime              0
snapshot_time            0
arrival_year             0
snapshot_year            0
snapshot_date            0
snapshot_hour            0
snapshot_minute          0
snapshot_second          0
departureTime            0
remaining_dwell_hours    0
dtype: int64

In [113]:
# drop arrival time and departure time from df
df = df.drop(columns=["arrivalTime", "departureTime"])
print(df.head())

   iedCode  reefer  teu    gross  arrivalLocationX  arrivalLocationY  \
0        0       0    1  27610.0                23                15
1        0       0    1  27610.0                23                15
2        0       0    1  27610.0                23                15
3        0       0    1  27610.0                23                15
4        0       0    1  27610.0                23                15

   arrivalLocationZ  released  numberOfArrivalContainersOnVessel  \
0                 8         1                               3398
1                 8         1                               3398
2                 8         1                               3398
3                 8         1                               3398
4                 8         1                               3398

   numberOfRemainOnBoardContainersOnVessel  \
0                                      899
1                                      899
2                                      899
3                                      899
4                                      899

   numberOfDepartureContainersOnVessel  temperature_2m  relative_humidity_2m  \
0                                 2120            18.8                    36
1                                 2120            18.8                    36
2                                 2121            18.8                    36
3                                 2121            18.8                    36
4                                 2121            18.8                    36

   precipitation  rain  weather_code  cloud_cover  wind_speed_10m  \
0            0.0   0.0             0            0             2.6
1            0.0   0.0             0            0             2.6
2            0.0   0.0             0            0             2.6
3            0.0   0.0             0            0             2.6
4            0.0   0.0             0            0             2.6

   wind_gusts_10m  is_raining  bad_weather_score  dwell_hours  iso_22GB  \
0            16.9           0                  0    50.946944         0
1            16.9           0                  0    50.946944         0
2            16.9           0                  0    50.946944         0
3            16.9           0                  0    50.946944         0
4            16.9           0                  0    50.946944         0

   iso_22K2  iso_22P3  iso_22R1  iso_22T1  iso_22T6  iso_22U1  iso_25G1  \
0         1         0         0         0         0         0         0
1         1         0         0         0         0         0         0
2         1         0         0         0         0         0         0
3         1         0         0         0         0         0         0
4         1         0         0         0         0         0         0

   iso_42G1  iso_42P3  iso_42U1  iso_45G0  iso_45G1  iso_45P3  iso_45R1  \
0         0         0         0         0         0         0         0
1         0         0         0         0         0         0         0
2         0         0         0         0         0         0         0
3         0         0         0         0         0         0         0
4         0         0         0         0         0         0         0

   iso_45R5  iso_45U1  iso_4EG1  iso_L5G1  iso_OTHER  arrival_hour  \
0         0         0         0         0          0            12
1         0         0         0         0          0            12
2         0         0         0         0          0            12
3         0         0         0         0          0            12
4         0         0         0         0          0            12

   arrival_dayofweek  arrival_month  arrival_is_weekend  arrival_hour_sin  \
0                  5              4                   1      1.224647e-16
1                  5              4                   1      1.224647e-16
2                  5              4                   1      1.224647e-16
3                  5              4                   1      1.224647e-16
4                  5              4                   1      1.224647e-16

   arrival_hour_cos  arrival_month_sin  arrival_month_cos  eta_error_hours  \
0              -1.0           0.866025               -0.5        45.721389
1              -1.0           0.866025               -0.5        45.721389
2              -1.0           0.866025               -0.5        45.721389
3              -1.0           0.866025               -0.5        45.721389
4              -1.0           0.866025               -0.5        45.721389

   arrivalPolCode_freq  arrivalVesselName_freq  \
0             0.142105                0.032369
1             0.142105                0.032369
2             0.142105                0.032369
3             0.142105                0.032369
4             0.142105                0.032369

   service_Arctic Container Lines AS  service_BOERDE  \
0                                  0               0
1                                  0               0
2                                  0               0
3                                  0               0
4                                  0               0

   service_Baltic Sea, etc (UNIFEEDER) FLZ  service_CMA CGM EPIC  \
0                                        0                     0
1                                        0                     0
2                                        0                     0
3                                        0                     0
4                                        0                     0

   service_CMA CGM FAL 1  service_CMA CGM FAL3  service_CMA CGM FEMEX  \
0                      0                     0                      0
1                      0                     0                      0
2                      0                     0                      0
3                      0                     0                      0
4                      0                     0                      0

   service_Diverse (absolute Ausnahme NUR Hauptschiffe)  service_EUROMAR  \
0                                                  0                   0
1                                                  0                   0
2                                                  0                   0
3                                                  0                   0
4                                                  0                   0

   service_FLX FINLAND EXPRESS  service_HSUD NEO SAMBA SAEC 1  \
0                            0                              0
1                            0                              0
2                            0                              0
3                            0                              0
4                            0                              0

   service_IOS - ME 1  service_LEVANTE  service_MAE EUROSAL/SAWC  \
0                   0                0                         0
1                   0                0                         0
2                   0                0                         0
3                   0                0                         0
4                   0                0                         0

   service_MAERSK E27  service_MAERSK Extra  service_MSC BRITANNIA  \
0                   0                     0                      0
1                   0                     0                      0
2                   0                     0                      0
3                   0                     0                      0
4                   0                     0                      0

   service_MSC EQUADOR/ BALTIC  service_MSC GREECE TURKEY  service_MSC IPAK  \
0                            0                          0                 0
1                            0                          0                 0
2                            0                          0                 0
3                            0                          0                 0
4                            0                          0                 0

   service_MSC NWC to IPAK  service_MSC SAF - SÜDAFRIKA  service_MSC SWAN  \
0                        0                            0                 0
1                        0                            0                 0
2                        0                            0                 0
3                        0                            0                 0
4                        0                            0                 0

   service_MSC-EXTRA  service_MSC/ZIM ISRAEL  service_NE 2  \
0                  0                       0             1
1                  0                       0             1
2                  0                       0             1
3                  0                       0             1
4                  0                       0             1

   service_NE 2 / AE1  service_NE 4  service_NE 4 / AE 5  \
0                   0             0                    0
1                   0             0                    0
2                   0             0                    0
3                   0             0                    0
4                   0             0                    0

   service_NEMO / AUSTRALIEN  service_NWL-Barge  \
0                          0                  0
1                          0                  0
2                          0                  0
3                          0                  0
4                          0                  0

   service_Norwegen (NORTH SEA CONTAINER LINE)  \
0                                            0
1                                            0
2                                            0
3                                            0
4                                            0

   service_Norwegendienst Westküste  service_PLX POLAND  \
0                                 0                   0
1                                 0                   0
2                                 0                   0
3                                 0                   0
4                                 0                   0

   service_RFS FEEDER IE1  service_RFS FEEDER IE2  \
0                       0                       0
1                       0                       0
2                       0                       0
3                       0                       0
4                       0                       0

   service_SBX BALTIC UNIF/CMA/ OOCL  service_SWX 2 SERVICE  \
0                                  0                      0
1                                  0                      0
2                                  0                      0
3                                  0                      0
4                                  0                      0

   service_WALTER LAUK  service_X-PRESS FEEDER  line_8  line_27  line_28  \
0                    0                       0       0        0        0
1                    0                       0       0        0        0
2                    0                       0       0        0        0
3                    0                       0       0        0        0
4                    0                       0       0        0        0

   line_32  line_33  line_42  line_64  line_67  line_68  line_70  line_77  \
0        0        0        0        0        0        0        0        0
1        0        0        0        0        0        0        0        0
2        0        0        0        0        0        0        0        0
3        0        0        0        0        0        0        0        0
4        0        0        0        0        0        0        0        0

   line_91  line_160  line_161  line_163  line_167  line_196  line_322  \
0        0         1         0         0         0         0         0
1        0         1         0         0         0         0         0
2        0         1         0         0         0         0         0
3        0         1         0         0         0         0         0
4        0         1         0         0         0         0         0

   arrivalType_BINNEN  arrivalType_FEEDER  arrivalType_OCEAN_CARRIER  \
0                   0                   0                          1
1                   0                   0                          1
2                   0                   0                          1
3                   0                   0                          1
4                   0                   0                          1

   arrivalType_SCHUTE  arrivalServiceCode_freq  type_AC  type_DC  type_DO  \
0                   0                 0.119635        0        0        0
1                   0                 0.119635        0        0        0
2                   0                 0.119635        0        0        0
3                   0                 0.119635        0        0        0
4                   0                 0.119635        0        0        0

   type_FC  type_FR  type_OH  type_OT  type_PL  type_RF  type_SR  type_TK  \
0        0        0        0        0        0        0        0        1
1        0        0        0        0        0        0        0        1
2        0        0        0        0        0        0        0        1
3        0        0        0        0        0        0        0        1
4        0        0        0        0        0        0        0        1

        snapshot_time  arrival_year  snapshot_year snapshot_date  \
0 2025-04-15 01:55:44          2025           2025    2025-04-15
1 2025-04-16 01:55:44          2025           2025    2025-04-16
2 2025-04-17 01:55:30          2025           2025    2025-04-17
3 2025-04-18 01:56:33          2025           2025    2025-04-18
4 2025-04-19 01:55:40          2025           2025    2025-04-19

   snapshot_hour  snapshot_minute  snapshot_second  remaining_dwell_hours
0              1               55               44                    0.0
1              1               55               44                    0.0
2              1               55               30                    0.0
3              1               56               33                    0.0
4              1               55               40                    0.0

In [114]:
df.to_csv("data/eurogate_train_encoded.csv", index=False)

In [117]:
print(df["remaining_dwell_hours"].describe())
print(df["remaining_dwell_hours"].value_counts().head())
print("Percent zero:", (df["remaining_dwell_hours"] == 0).mean())

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: remaining_dwell_hours, dtype: float64
Series([], Name: count, dtype: int64)
Percent zero: nan

In [116]:
df = df.reset_index(drop=True)
df_original = df_original.reset_index(drop=True)

valid_idx = df_original["remaining_dwell_hours"] > 0

df = df.loc[valid_idx].reset_index(drop=True)
df_original = df_original.loc[valid_idx].reset_index(drop=True)

df["remaining_dwell_hours"] = df_original["remaining_dwell_hours"].values

In [120]:
import pandas as pd
import numpy as np

RAW_CSV = "data/eurogate_all_snapshots.csv"
OUTPUT_CSV = "data/eurogate_predeparture_remaining_dwell.csv"

df_raw = pd.read_csv(RAW_CSV)

# -----------------------------
# Datetime setup
# -----------------------------
df_raw["arrivalTime"] = pd.to_datetime(df_raw["arrivalTime"], errors="coerce", utc=True)
df_raw["departureTime"] = pd.to_datetime(df_raw["departureTime"], errors="coerce", utc=True)
df_raw["arrivalVoyageEta"] = pd.to_datetime(df_raw["arrivalVoyageEta"], errors="coerce", utc=True)

df_raw["snapshot_time"] = (
    df_raw["source_file"]
    .str.extract(r"Containerdaten-(\d{4}-\d{2}-\d{2}_\d{2}\.\d{2}\.\d{2})")[0]
    .str.replace("_", " ", regex=False)
    .str.replace(".", ":", regex=False)
)

df_raw["snapshot_time"] = pd.to_datetime(
    df_raw["snapshot_time"],
    errors="coerce",
    utc=True
)

# -----------------------------
# Get final departure time per container
# -----------------------------
final_departure = (
    df_raw.dropna(subset=["departureTime"])
    .groupby("containerId")["departureTime"]
    .min()
    .rename("final_departureTime")
)

df_raw = df_raw.merge(
    final_departure,
    on="containerId",
    how="left"
)

# -----------------------------
# Keep only pre-departure snapshots
# -----------------------------
df_pre = df_raw[
    df_raw["departureTime"].isna()
    & df_raw["final_departureTime"].notna()
    & (df_raw["snapshot_time"] < df_raw["final_departureTime"])
].copy()

print("Pre-departure rows:", len(df_pre))
print("Unique containers:", df_pre["containerId"].nunique())

if len(df_pre) == 0:
    raise ValueError("No valid pre-departure snapshots found.")

# -----------------------------
# Target variables
# -----------------------------
df_pre["remaining_dwell_hours"] = (
    df_pre["final_departureTime"] - df_pre["snapshot_time"]
).dt.total_seconds() / 3600

df_pre["dwell_hours"] = (
    df_pre["final_departureTime"] - df_pre["arrivalTime"]
).dt.total_seconds() / 3600

# -----------------------------
# Arrival time features
# -----------------------------
df_pre["arrival_hour"] = df_pre["arrivalTime"].dt.hour
df_pre["arrival_dayofweek"] = df_pre["arrivalTime"].dt.dayofweek
df_pre["arrival_month"] = df_pre["arrivalTime"].dt.month
df_pre["arrival_is_weekend"] = (df_pre["arrival_dayofweek"] >= 5).astype(int)

df_pre["arrival_hour_sin"] = np.sin(2 * np.pi * df_pre["arrival_hour"] / 24)
df_pre["arrival_hour_cos"] = np.cos(2 * np.pi * df_pre["arrival_hour"] / 24)
df_pre["arrival_month_sin"] = np.sin(2 * np.pi * df_pre["arrival_month"] / 12)
df_pre["arrival_month_cos"] = np.cos(2 * np.pi * df_pre["arrival_month"] / 12)

df_pre["eta_error_hours"] = (
    df_pre["arrivalTime"] - df_pre["arrivalVoyageEta"]
).dt.total_seconds() / 3600

# -----------------------------
# Snapshot time features
# -----------------------------
df_pre["arrival_year"] = df_pre["arrivalTime"].dt.year
df_pre["snapshot_year"] = df_pre["snapshot_time"].dt.year
df_pre["snapshot_date"] = df_pre["snapshot_time"].dt.strftime("%Y-%m-%d")
df_pre["snapshot_hour"] = df_pre["snapshot_time"].dt.hour
df_pre["snapshot_minute"] = df_pre["snapshot_time"].dt.minute
df_pre["snapshot_second"] = df_pre["snapshot_time"].dt.second

df_pre["elapsed_dwell_hours"] = (
    df_pre["snapshot_time"] - df_pre["arrivalTime"]
).dt.total_seconds() / 3600

df_pre = df_pre[df_pre["elapsed_dwell_hours"] >= 0].copy()

# -----------------------------
# Binary encoding
# -----------------------------
df_pre["iedCode"] = df_pre["iedCode"].map({
    "IMPORT": 0,
    "EXPORT": 1
})

df_pre["reefer"] = df_pre["reefer"].map({
    True: 1,
    False: 0,
    "True": 1,
    "False": 0,
    1: 1,
    0: 0
})

df_pre["released"] = df_pre["released"].map({
    "Y": 1,
    "N": 0,
    1: 1,
    0: 0
})

# -----------------------------
# Frequency encodings
# -----------------------------
arrival_pol_freq = df_raw["arrivalPolCode"].value_counts(normalize=True)
vessel_freq = df_raw["arrivalVesselName"].value_counts(normalize=True)
service_code_freq = df_raw["arrivalServiceCode"].value_counts(normalize=True)

df_pre["arrivalPolCode_freq"] = df_pre["arrivalPolCode"].map(arrival_pol_freq)
df_pre["arrivalVesselName_freq"] = df_pre["arrivalVesselName"].map(vessel_freq)
df_pre["arrivalServiceCode_freq"] = df_pre["arrivalServiceCode"].map(service_code_freq)

# -----------------------------
# ISO top 20 + OTHER
# -----------------------------
top20_iso = df_raw["sizetypeIsoCode"].value_counts().nlargest(20).index

df_pre["sizetypeIsoCode_clean"] = np.where(
    df_pre["sizetypeIsoCode"].isin(top20_iso),
    df_pre["sizetypeIsoCode"],
    "OTHER"
)

df_pre = pd.get_dummies(
    df_pre,
    columns=["sizetypeIsoCode_clean"],
    prefix="iso",
    drop_first=False
)

# -----------------------------
# One-hot encode categorical columns
# -----------------------------
df_pre = pd.get_dummies(
    df_pre,
    columns=[
        "arrivalServiceName",
        "lineCode",
        "arrivalType",
        "typeCode"
    ],
    prefix=[
        "service",
        "line",
        "arrivalType",
        "type"
    ],
    drop_first=False
)

bool_cols = df_pre.select_dtypes(include=["bool"]).columns
df_pre[bool_cols] = df_pre[bool_cols].astype(int)

# -----------------------------
# Drop raw/non-model columns
# -----------------------------
drop_cols = [
    "containerId",
    "customsRefId",
    "mgw",
    "csc",
    "originOfTransportCode",
    "arrivalTime",
    "arrivalPolCode",
    "arrivalVoyageEta",
    "arrivalVesselName",
    "arrivalServiceCode",
    "departureTime",
    "departureType",
    "destinationCode",
    "forwarderName",
    "source_file",
    "location_key",
    "weather_match_time",
    "weather_hour",
    "weather_time",
    "final_departureTime",
    "sizetypeIsoCode"
]

df_pre = df_pre.drop(
    columns=[c for c in drop_cols if c in df_pre.columns]
)

# -----------------------------
# Reorder important columns first
# -----------------------------
front_cols = [
    "remaining_dwell_hours",
    "dwell_hours",
    "elapsed_dwell_hours",
    "iedCode",
    "reefer",
    "teu",
    "gross",
    "arrivalLocationX",
    "arrivalLocationY",
    "arrivalLocationZ",
    "released",
    "numberOfArrivalContainersOnVessel",
    "numberOfRemainOnBoardContainersOnVessel",
    "numberOfDepartureContainersOnVessel",
    "temperature_2m",
    "relative_humidity_2m",
    "precipitation",
    "rain",
    "weather_code",
    "cloud_cover",
    "wind_speed_10m",
    "wind_gusts_10m",
    "is_raining",
    "bad_weather_score",
    "arrival_hour",
    "arrival_dayofweek",
    "arrival_month",
    "arrival_is_weekend",
    "arrival_hour_sin",
    "arrival_hour_cos",
    "arrival_month_sin",
    "arrival_month_cos",
    "eta_error_hours",
    "arrivalPolCode_freq",
    "arrivalVesselName_freq",
    "arrivalServiceCode_freq",
    "snapshot_time",
    "arrival_year",
    "snapshot_year",
    "snapshot_date",
    "snapshot_hour",
    "snapshot_minute",
    "snapshot_second"
]

front_cols = [c for c in front_cols if c in df_pre.columns]
other_cols = [c for c in df_pre.columns if c not in front_cols]

df_pre = df_pre[front_cols + other_cols]

# -----------------------------
# Clean missing/infinite values
# -----------------------------
df_pre = df_pre.replace([np.inf, -np.inf], np.nan)

numeric_cols = df_pre.select_dtypes(include=[np.number]).columns
df_pre[numeric_cols] = df_pre[numeric_cols].fillna(df_pre[numeric_cols].median())

# -----------------------------
# Final checks
# -----------------------------
print("\nFinal shape:", df_pre.shape)

print("\nRemaining dwell summary:")
print(df_pre["remaining_dwell_hours"].describe())

print("\nPercent zero remaining dwell:")
print((df_pre["remaining_dwell_hours"] == 0).mean())

print("\nObject columns:")
print(df_pre.select_dtypes(include=["object"]).columns.tolist())

# -----------------------------
# Save
# -----------------------------
df_pre.to_csv(OUTPUT_CSV, index=False)

print("\nSaved:", OUTPUT_CSV)

Pre-departure rows: 334633
Unique containers: 92295

Final shape: (334633, 124)

Remaining dwell summary:
count    334633.000000
mean         88.205058
std         113.423944
min           0.002500
25%          27.592500
50%          59.744444
75%         117.293889
max        4225.116944
Name: remaining_dwell_hours, dtype: float64

Percent zero remaining dwell:
0.0

Object columns:
['snapshot_date']

Saved: data/eurogate_predeparture_remaining_dwell.csv

In [122]:
df_pre = pd.read_csv("data/eurogate_predeparture_remaining_dwell.csv")
# print all columns and a sample of values for each column
# for col in df_pre.columns:
#     print(f"\nColumn: {col}")
#     print(df_pre[col].value_counts(dropna=False).head(10))

df_pre.head()

,remaining_dwell_hours,dwell_hours,elapsed_dwell_hours,iedCode,reefer,teu,gross,arrivalLocationX,arrivalLocationY,arrivalLocationZ,released,numberOfArrivalContainersOnVessel,numberOfRemainOnBoardContainersOnVessel,numberOfDepartureContainersOnVessel,arrival_hour,arrival_dayofweek,arrival_month,arrival_is_weekend,arrival_hour_sin,arrival_hour_cos,arrival_month_sin,arrival_month_cos,eta_error_hours,arrivalPolCode_freq,arrivalVesselName_freq,arrivalServiceCode_freq,snapshot_time,arrival_year,snapshot_year,snapshot_date,snapshot_hour,snapshot_minute,snapshot_second,iso_22G0,iso_22G1,iso_22GB,iso_22K2,iso_22P3,iso_22R1,iso_22T1,iso_22T6,iso_22U1,iso_25G1,iso_42G1,iso_42P3,iso_42U1,iso_45G0,iso_45G1,iso_45P3,iso_45R1,iso_45R5,iso_45U1,iso_L5G1,iso_OTHER,service_2M AE7 / CONDOR,service_Arctic Container Lines AS,service_BOERDE,"service_Baltic Sea, etc (UNIFEEDER) FLZ",service_CMA CGM EPIC,service_CMA CGM FAL 1,service_CMA CGM FAL3,service_CMA CGM FEMEX,service_EUROMAR,service_FLX FINLAND EXPRESS,service_HSUD NEO SAMBA SAEC 1,service_IOS - ME 1,service_LEVANTE,service_MAE EUROSAL/SAWC,service_MAERSK E27,service_MAERSK Extra,service_MSC EQUADOR/ BALTIC,service_MSC GREECE TURKEY,service_MSC IPAK,service_MSC SAF - SÜDAFRIKA,service_MSC SWAN,service_MSC-EXTRA,service_MSC/ZIM ISRAEL,service_NE 2,service_NE 2 / AE1,service_NE 4,service_NE 4 / AE 5,service_NEMO / AUSTRALIEN,service_NWL-Barge,service_Norwegen (NORTH SEA CONTAINER LINE),service_Norwegendienst Westküste,service_PLX POLAND,service_RFS FEEDER IE1,service_SBX BALTIC UNIF/CMA/ OOCL,service_SWX 2 SERVICE,service_WALTER LAUK,service_X-PRESS FEEDER,line_1,line_8,line_27,line_28,line_32,line_33,line_42,line_64,line_67,line_68,line_70,line_77,line_91,line_160,line_163,line_167,line_196,line_322,arrivalType_BINNEN,arrivalType_FEEDER,arrivalType_OCEAN_CARRIER,arrivalType_SCHUTE,type_AC,type_DC,type_DO,type_FC,type_FR,type_OH,type_OT,type_PL,type_RF,type_SR,type_TK
0,37.731389,50.946944,13.215556,0,0,1,27610.0,23,15,8,1,3398,899,2120,12,5,4,1,1.224647e-16,-1.000000,0.866025,-5.000000e-01,45.721389,0.138465,0.031550,0.129979,2025-04-13 01:56:13+00:00,2025,2025,2025-04-13,1,56,13,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
1,13.731389,50.946944,37.215556,0,0,1,27610.0,23,15,8,1,3398,899,2120,12,5,4,1,1.224647e-16,-1.000000,0.866025,-5.000000e-01,45.721389,0.138465,0.031550,0.129979,2025-04-14 01:56:13+00:00,2025,2025,2025-04-14,1,56,13,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
2,12.016111,25.929167,13.913056,0,0,1,21850.0,27,4,6,1,724,578,574,12,2,4,0,1.224647e-16,-1.000000,0.866025,-5.000000e-01,10.011944,0.007662,0.005168,0.042040,2025-04-17 01:55:30+00:00,2025,2025,2025-04-17,1,55,30,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
3,5.673611,17.947778,12.274167,0,0,1,21690.0,45,8,8,1,724,578,574,13,2,4,0,-2.588190e-01,-0.965926,0.866025,-5.000000e-01,11.650833,0.007662,0.005168,0.042040,2025-04-17 01:55:30+00:00,2025,2025,2025-04-17,1,55,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
4,126.931111,129.004722,2.073611,1,1,1,19327.0,45,0,82,0,634,2230,1216,23,0,3,0,-2.588190e-01,0.965926,1.000000,6.123234e-17,3.356111,0.010462,0.005157,0.042040,2025-04-01 01:55:47+00:00,2025,2025,2025-04-01,1,55,47,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0

In [124]:
df = pd.read_csv("data/eurogate_train_encoded.csv")
df.head()

,iedCode,reefer,teu,gross,arrivalLocationX,arrivalLocationY,arrivalLocationZ,released,numberOfArrivalContainersOnVessel,numberOfRemainOnBoardContainersOnVessel,numberOfDepartureContainersOnVessel,temperature_2m,relative_humidity_2m,precipitation,rain,weather_code,cloud_cover,wind_speed_10m,wind_gusts_10m,is_raining,bad_weather_score,dwell_hours,iso_22GB,iso_22K2,iso_22P3,iso_22R1,iso_22T1,iso_22T6,iso_22U1,iso_25G1,iso_42G1,iso_42P3,iso_42U1,iso_45G0,iso_45G1,iso_45P3,iso_45R1,iso_45R5,iso_45U1,iso_4EG1,iso_L5G1,iso_OTHER,arrival_hour,arrival_dayofweek,arrival_month,arrival_is_weekend,arrival_hour_sin,arrival_hour_cos,arrival_month_sin,arrival_month_cos,eta_error_hours,arrivalPolCode_freq,arrivalVesselName_freq,service_Arctic Container Lines AS,service_BOERDE,"service_Baltic Sea, etc (UNIFEEDER) FLZ",service_CMA CGM EPIC,service_CMA CGM FAL 1,service_CMA CGM FAL3,service_CMA CGM FEMEX,service_Diverse (absolute Ausnahme NUR Hauptschiffe),service_EUROMAR,service_FLX FINLAND EXPRESS,service_HSUD NEO SAMBA SAEC 1,service_IOS - ME 1,service_LEVANTE,service_MAE EUROSAL/SAWC,service_MAERSK E27,service_MAERSK Extra,service_MSC BRITANNIA,service_MSC EQUADOR/ BALTIC,service_MSC GREECE TURKEY,service_MSC IPAK,service_MSC NWC to IPAK,service_MSC SAF - SÜDAFRIKA,service_MSC SWAN,service_MSC-EXTRA,service_MSC/ZIM ISRAEL,service_NE 2,service_NE 2 / AE1,service_NE 4,service_NE 4 / AE 5,service_NEMO / AUSTRALIEN,service_NWL-Barge,service_Norwegen (NORTH SEA CONTAINER LINE),service_Norwegendienst Westküste,service_PLX POLAND,service_RFS FEEDER IE1,service_RFS FEEDER IE2,service_SBX BALTIC UNIF/CMA/ OOCL,service_SWX 2 SERVICE,service_WALTER LAUK,service_X-PRESS FEEDER,line_8,line_27,line_28,line_32,line_33,line_42,line_64,line_67,line_68,line_70,line_77,line_91,line_160,line_161,line_163,line_167,line_196,line_322,arrivalType_BINNEN,arrivalType_FEEDER,arrivalType_OCEAN_CARRIER,arrivalType_SCHUTE,arrivalServiceCode_freq,type_AC,type_DC,type_DO,type_FC,type_FR,type_OH,type_OT,type_PL,type_RF,type_SR,type_TK,snapshot_time,arrival_year,snapshot_year,snapshot_date,snapshot_hour,snapshot_minute,snapshot_second,remaining_dwell_hours
0,0,0,1,27610.0,23,15,8,1,3398,899,2120,18.8,36,0.0,0.0,0,0,2.6,16.9,0,0,50.946944,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,5,4,1,1.224647e-16,-1.0,0.866025,-0.5,45.721389,0.142105,0.032369,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0.119635,0,0,0,0,0,0,0,0,0,0,1,2025-04-15 01:55:44,2025,2025,2025-04-15,1,55,44,0.0
1,0,0,1,27610.0,23,15,8,1,3398,899,2120,18.8,36,0.0,0.0,0,0,2.6,16.9,0,0,50.946944,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,5,4,1,1.224647e-16,-1.0,0.866025,-0.5,45.721389,0.142105,0.032369,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0.119635,0,0,0,0,0,0,0,0,0,0,1,2025-04-16 01:55:44,2025,2025,2025-04-16,1,55,44,0.0
2,0,0,1,27610.0,23,15,8,1,3398,899,2121,18.8,36,0.0,0.0,0,0,2.6,16.9,0,0,50.946944,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,5,4,1,1.224647e-16,-1.0,0.866025,-0.5,45.721389,0.142105,0.032369,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0.119635,0,0,0,0,0,0,0,0,0,0,1,2025-04-17 01:55:30,2025,2025,2025-04-17,1,55,30,0.0
3,0,0,1,27610.0,23,15,8,1,3398,899,2121,18.8,36,0.0,0.0,0,0,2.6,16.9,0,0,50.946944,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,5,4,1,1.224647e-16,-1.0,0.866025,-0.5,45.721389,0.142105,0.032369,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0.119635,0,0,0,0,0,0,0,0,0,0,1,2025-04-18 01:56:33,2025,2025,2025-04-18,1,56,33,0.0
4,0,0,1,27610.0,23,15,8,1,3398,899,2121,18.8,36,0.0,0.0,0,0,2.6,16.9,0,0,50.946944,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,5,4,1,1.224647e-16,-1.0,0.866025,-0.5,45.721389,0.142105,0.032369,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0.119635,0,0,0,0,0,0,0,0,0,0,1,2025-04-19 01:55:40,2025,2025,2025-04-19,1,55,40,0.0

In [125]:
# drop remaining dwell hours from df 
df = df.drop(columns=["remaining_dwell_hours"])
df.to_csv("data/eurogate_train_encoded.csv", index=False)